### ISSUE TITLE
Object doesn't support this action File: ie8.js, Line: 2, Column: 190

### ISSUE THREAD

**Issue by adyen-martinhagedoorn** [WebReflection/document-register-element#103]
Tested this example: http://webreflection.github.io/document-register-element/test/examples/x-map.html

And got the following error in IE8 :
HTML1300: Navigation occurred. File: x-map.html value failed on object: [object HTMLSelectElement] Object doesn't support this action "value failed on object:" { } "Object doesn't support this action" SCRIPT445: Object doesn't support this action File: ie8.js, Line: 2, Column: 190

Used VirtualBox with Windows 8.1 and IE11 with emulation of IE8

**Comment by WebReflection** [comment]
>  IE11 with emulation of IE8

when you'll find a bug with the real IE8 instead please let me know
