### ISSUE TITLE
V1 Caveat examples not compatible with TypeScript

### ISSUE THREAD

**Issue by nicobrinkkemper** [WebReflection/document-register-element#104]
The first example gives the following warning:
`supplied parameters do not match any signature of call target`
The second example gives the following warning:
`super() constructor call must be the first statement in a constructor`

Is there a known fix for this?

**Comment by WebReflection** [comment]
I've no idea about TypeScript so probably the best place to ask about classes issues in TypeScript is TypeScript repository?

If you just use JavaScript it works as expected.

Unless you transpile, of course, but that's another story and still not a bug for this repository.

**Comment by cronon** [comment]
@nicobrinkkemper have you solved it?

**Comment by nicobrinkkemper** [comment]
No. This issue still prevents me from using the constructor in any useful way. I work around it by using the connectedCallback instead. You can extend it by calling super.connectedCallback();

**Comment by WebReflection** [comment]
> without any caveat none sense

if you understand why caveat is needed on Babel, you'll realize that's everything but a non-sense.

About connectedCallback as fallback for the constructor, watch out it might be called **after** attributesChangedCallback.

Slide explaining the issue: https://twitter.com/WebReflection/status/869168688355844096

Video about Custom Elements: https://www.youtube.com/watch?v=rYol466ngVM

**Comment by cronon** [comment]
If it would be helpful, I've managed to run custom-elements with
```ts
export class MyElement extends HTMLElement {
    constructor(self?: any) {
        super();
        // if document-register-element has been loaded
        if (self) {
            self = HTMLElement.call(this, self);
            self.init();
            return self;
        } else {
            this.init();
        }
    }
    protected init(): void {
        //
    }
```
And it's transpiled into
```js
var MyElement = (function (_super) {
    __extends(MyElement, _super);
    function MyElement(self) {
        var _this = _super.call(this) || this;
        _this._connected = false;
        // if document-register-element has been loaded
        if (self) {
            self = HTMLElement.call(_this, self);
            self.init();
            return self;
        }
        else {
            _this.init();
        }
        return _this;
    }

    MyElement.prototype.init = function () {
        //
    };
```
We also use [native-shim](https://github.com/webcomponents/custom-elements/blob/master/src/native-shim.js) for es5 code to run in Chrome

**Comment by WebReflection** [comment]
@cronon if you use `init` why didn't you simply follow [these instructions](https://github.com/WebReflection/document-register-element#skipping-the-caveat-through-extends)?

```js
// base class to extend, same trick as before
class HTMLCustomElement extends HTMLElement {
  constructor(_) { return (_ = super(_)).init(), _; }
  init() { /* override as you like */ }
}

// create any other class inheriting HTMLCustomElement
class MyElement extends HTMLCustomElement {
  init() {
    // just use `this` as regular
    this.addEventListener('click', console.log);
    // no need to return it
  }
}
```

**Comment by cronon** [comment]
because typescript believes it is not a super call:)
and throws `A 'super' call must be the first statement in the constructor when a class contains initialized properties or has parameter properties`

**Comment by WebReflection** [comment]
I'll never get why people like causing themselves problems branching out so badly from specifications.

Anyway, in your suggestion, if the polyfill is patching classes, there are 3 new instances per each new component where 2 of them are instantly thrown away and no engine can optimize that.

My example doesn't waste operations.

**Moreover** I can test this on the playground without any issue.

```js
class Wut extends Object {
  constructor(_) { return (_ = super(_)), _; }
}

new Wut(); // all good
```

Which is the exact same procedure I'm using in my example.

Wht is going on in TypeScript?

**Comment by nicobrinkkemper** [comment]
That won't work extending HTMLElement, because the constructor (super) doesn't take a parameter.

`class Wut extends HTMLElement {
  constructor(_) { return (_ = super(_)), _; }
}

new Wut(); // Supplied parameters do not match any signature of call target.`

**Comment by WebReflection** [comment]
sorry I've been busy with other stuff but I'll think about a solution, if any.

**Comment by nicobrinkkemper** [comment]
I came across this solution. Would this in theory also work for document-register-element

**Comment by WebReflection** [comment]
I don't know about that but its' very first example, regardless the custom elements, has the most common and obvious bug I know.

![screenshot from 2017-06-20 12-42-50](https://user-images.githubusercontent.com/85749/27331675-657ed1fa-55b6-11e7-91f1-5c6fad0d36b9.png)
