### ISSUE TITLE
1.5.0 is not published

### ISSUE THREAD

**Issue by albertosantini** [WebReflection/document-register-element#108]
It seems release `1.5.0` is not published.

I would add in the section `via CDN` of README also the `unpkg` link:
`<script src="https://unpkg.com/document-register-element/build/document-register-element.js"></script>`

The short link `https://unpkg.com/document-register-element` doesn't work because `main` in package.json points to node version.

**Comment by WebReflection** [comment]
I should put a hook there ... thanks for pointing this out.

It's published now.

**Comment by albertosantini** [comment]
Thanks.

It is published, but now I think your forgot to add the tag `v1.5.0` to the repo. :)

**Comment by WebReflection** [comment]
gosh ... done, sorry
