### ISSUE TITLE
Can we detect if polyfill was applied or not?

### ISSUE THREAD

**Issue by MikeVaz** [WebReflection/document-register-element#111]
The case I am working on requires to detect if polyfill is used or not. 

From the source code I can see that it can have modes based on the polyfill flag. And it detects if V1 or V0 is supported. Can we save it somewhere for further reference.

We can do it before including a polyfill but this would require a Critical Rendering Path blocking Javascript. 

Additionally it would be cool to use V0 native implementation in Chrome when possible.

**Comment by MikeVaz** [comment]
But I have a choice to use customElement.define or registerElement right? But I see your point that polyfill already made a better choice for me.

**Comment by WebReflection** [comment]
> But I have a choice to use customElement.define or registerElement right?

not really ... you should use `customElement.define` which has better/wider native support and it polyfills native extends through V0 API where available (or the poly code that enables it)

So no. You should not use deprecated/death standards, you should simply put the polyfill and forget about it until you can remove it, plus always use the current standard which is `customElements` registry.

**Comment by MikeVaz** [comment]
The difference in my case is that customElement.define requires extra work before I can use it. But registerElement is cheaper.

**Comment by WebReflection** [comment]
It's your code, you decide how to write it. This polyfills give you both V0 and V1 for every supported browser. I'd go V1 if possible, you can go V0 as well ... but this has nothing to do with this polyfill, isn't it? :smile:

**Comment by WebReflection** [comment]
P.S. nothing really stops you to `var V0 = 'registerElement' in document, V1 = 'customElements' in window;` on top of your pages
