### ISSUE TITLE
Bug with connectedCallback in Chrome

### ISSUE THREAD

**Issue by MikeVaz** [WebReflection/document-register-element#112]
It is not a polyfill bug but I want to share with you this observation. connectedCallback doesn't work as expected when we put a <script> tag with definitions between two elements <my-element-1> in the code of the page. 
```HTML
<my-element-1> I am custom element </my-element-1>
<script>
class myComponent1 extends HTMLElement {
	constructor() {
  		super();
  	}
  	connectedCallback() {
  		this.innerHTML += '<b>Hello!</b>';
  	}
}

customElements.define('my-element-1', myComponent1);
</script>
<br>
<my-element-1> I am custom element </my-element-1>
```
Expect *Hello!* to be at the end of the contents of the elements regardless of where we define our custom element.

https://jsfiddle.net/webrealizer/m9qec0nv/

**Comment by WebReflection** [comment]
Have you tried without this polyfill at all?

**Comment by MikeVaz** [comment]
This happens without a polyfill.  As it shown in the jsfiddle link I provided. It is likely a Chrome bug.

**Comment by WebReflection** [comment]
On Safari it's all good and I won't fix this on the polyfill or I need to fully patch Chrome. Have you filed a bug for chromium?

**Comment by MikeVaz** [comment]
Submitted: https://bugs.chromium.org/p/chromium/issues/detail?id=739417
