### ISSUE TITLE
Non-expected behavior with HyperElement

### ISSUE THREAD

**Issue by aliaksandr-yermalayeu** [WebReflection/document-register-element#116]
Here is [bin](http://jsbin.com/vorexed/edit?html,js,console) to demonstrate the issue.

Steps to reproduce:
1) Open bin in Firefox. Look at console.
2) Try replacing document-register-element with webcomponents polyfill. Everything should work fine.

**Comment by aliaksandr-yermalayeu** [comment]
The issue is, "this" context differs in _constructor_ and _created_ methods, while it stays the same in browsers with _custom elements_ support, or using different polyfill.

**Comment by WebReflection** [comment]
this bin http://jsbin.com/coqajiwuwu/edit?html,js,console

shows how you should use the constructor, which is described in this repository README.

HyperHTMLElement simplifies everything for you exposing the `created` method, which is the one you should use to setup your components.

This will grant you the perfect time to do such setup, which is not always the `constructor`, neither the `connectedCallback` or the `attributeChangedCallback`, and it will let you forget about constructor issues with both transpiled and not transpiled code.
