### ISSUE TITLE
querySelectorAll errors when no registered elements exist

### ISSUE THREAD

**Issue by mmclau14** [WebReflection/document-register-element#117]
title says it all. function errors on up to date ff. I would rather not put a try on the other side since if this shim has to be implemented elsewhere it will need the exact same logic

<img width="301" alt="screen shot 2017-09-28 at 1 02 45 pm" src="https://user-images.githubusercontent.com/4896982/30982547-595e17a6-a44d-11e7-9ba6-fbd8aa5dd9f7.png">

**Comment by WebReflection** [comment]
what is this error about?

`querySelectorAll` is performed only when `query` has a length so I don't understand

https://github.com/WebReflection/document-register-element/blob/master/src/document-register-element.js#L521

https://github.com/WebReflection/document-register-element/blob/master/src/document-register-element.js#L571-L574

https://github.com/WebReflection/document-register-element/blob/master/src/document-register-element.js#L633-L636

https://github.com/WebReflection/document-register-element/blob/master/src/document-register-element.js#L701-L704

**Comment by mmclau14** [comment]
the querySelector all is in the shim itself.

```javascript
nodes = el.querySelectorAll(registered.join(',')),```

**Comment by mmclau14** [comment]
Super, thanks!

**Comment by WebReflection** [comment]
it's not in the package or the CDN yet, but that file has been changed.
Please let me know if it works so I can bump a patch version, thanks.

**Comment by mmclau14** [comment]
seems to work. Firefox no longer throws
before: https://jsfiddle.net/wk1ytm5a/2/
after: https://jsfiddle.net/wk1ytm5a/1/
