### ISSUE TITLE
Order of reactions' execution

### ISSUE THREAD

**Issue by cronon** [WebReflection/document-register-element#119]
I know that reaction callbacks are run asynchronously, but is the order of their execution kept?

Just found that `connectedCallback` is called before `attributeChangedCallback` if custom element is rendered by angular.
https://jsfiddle.net/36x4s44w/2/
I've been investigating this, but still have no idea what goes wrong

**Comment by WebReflection** [comment]
that's how native works too. The order in which `attributeChangedCallback` and `connectecCallback` are triggered is completely arbitrary. There's no rule whatsoever because these two methods are not correlated at all.

**Comment by WebReflection** [comment]
P.S. if what you need is an init event, you can use a very simple work around

```js
class HTMLInitElement extends HTMLElement {
  static init() {}
  init() {
    // init should never happen more than once
    // so, make it a no-op from now on
    this.init = HTMLInitElement.init;
  }
  attributeChangedCallback(...args) {
    this.init();
  }
  connectedCallback() {
    this.init();
  }
}

class MyEl extends HTMLInitElement {
  static get observedAttributes() { return ['test']; }
  init() {
    super.init();
    console.log('init');
  }
  attributeChangedCallback(...args) {
    super.attributeChangedCallback(...args);
    console.log('attributeChangedCallback');
  }
  connectedCallback() {
    super.connectedCallback();
    console.log('connectedCallback');
  }
}

customElements.define('my-el', MyEl);

document.body.innerHTML = '<my-el></my-el><my-el test=123></my-el>';
```

**Comment by cronon** [comment]
@WebReflection thanks for explanation!
