### ISSUE TITLE
'Assertion failed' in Safari if you use WCv0 polyfill and V1 syntax in your component

### ISSUE THREAD

**Issue by alshakero** [WebReflection/document-register-element#128]
Here is a very simple JSBin that illustrates the issue. 

https://jsbin.com/faruba/edit?html,js,output

Potentially important notes: 
- If you use WCv1 polyfill it works.
- If you use WCv0 syntax (`attachedCallback` etc) in your compontent, it works.

But I guess you can tell both of these hacks would defy the purpose of this polyfill.

**Comment by WebReflection** [comment]
I will never ever consider any bug for a page that includes webcomponents.js upfront

if you use this polyfill, you don't need webcomponents.js
