### ISSUE TITLE
Data Not Updating

### ISSUE THREAD

**Issue by 6button9** [WebReflection/document-register-element#129]
I created a directory data at the same level as the component directory and created a file my-data.tsx. In the tsx file I put several objects of arrays of string data and a function or two.

I use the data in several of the components, I created and access it by importing the objects.

First compile everything appears to work fine. Upon changing the data in the data.tsx file and saving the file to recompile the data is not updated in the running test website.

I am using the const keyword to declare my objects. If I delete the const keyword and save to recompile, to force a compiler error and then put the const back and re-save. To re-compile again. Everything works and all the data updates as expected.

I am using Ubuntu 16.04, Chrome and Atom.

Thanks for the Great Product,
John Sutton
jasutton3@gmail.com

**Comment by WebReflection** [comment]
I have no idea what you are talking about.

Please provide an example code of what you are doing, thanks.

**Comment by 6button9** [comment]
Andrea,

Thanks for replying.

I put my source files on git hub.
https://github.com/6button9/Stencil_Test

I feel this is a minor issue and is probably due to some files not properly
refresing when the npm watcher attempts to compile the code.

I am just starting to learn Stencil and I am working on mocking up a
website's general interface.
In the src/data sub-directory I created a file my-data.tsx to store and
manage my data and build arrays to fill my menus.

This is a very short and sample piece of the code that I put on git hub.

export const topMenus = [
  'Top',
  'two',
  'three',
  'four',
  'five',
  'six',
]


The issue is when I change some of the data in the my-data.txt file. Say,
in the code above I changed "Top" to "NotTopAnyMore". Then I save the file.
Because the npm watch is set-up, by Stencil, npm re compiles the code for
the app and refreshes the site on the server. I know it succeeds, because I
can visually see the webpage refresh in the browser (localhost:3333) and no
errors show up in the Linux terminal. The modified data is not displayed
and the old data is still shown as the text in the menu.  The menu in this
case still says "Top" and not "NotTopAnyMore".

Then to fix the problem, get the page data to match the TypeScript data, I
purposely make the Stencil Compiler crash, by writing code that I know will
cause a compilation error. Then I fix the code, re-save. Thus, causing npm
watch to re-compile the app and the data on the page, in this case
"NotTopAnyMore" is displayed correctly.

So, for some reason, the compiler is not picking up my code changes in the
data file.

I hope this make more sense.

Thanks,

John Sutton

On Sat, Oct 28, 2017 at 3:03 PM, Andrea Giammarchi <notifications@github.com

**Comment by WebReflection** [comment]
I don't know much about stencil ... maybe asking there would be more appropriate?

**Comment by 6button9** [comment]
Andrea,

I just tried to re-create the problem and it is not happening anymore.

It could have been a glich in my system.

Kinda ghost in the machine type thing, I guess.

Thanks Again,

John Sutton

**Comment by 6button9** [comment]
Andrea,

I am really sorry, I thought I was at the Stencil Issues board and not git
hub.

Thanks again for attempting to be so helpful.

On Sun, Oct 29, 2017 at 9:58 AM, Andrea Giammarchi <notifications@github.com

**Comment by MikeVaz** [comment]
This is so funny at many levels. You made my day :) Stencil, Typescript, Magic fix.
