### ISSUE TITLE
Running npm test

### ISSUE THREAD

**Issue by opinel** [WebReflection/document-register-element#13]
Hi,

Thanks for the great polyfill. :-)
When running make for the project, there are no tests executed. Is there a twist to make the test work from the command line or are they currently not working?

**Comment by WebReflection** [comment]
tests are run via `index.html` and also [published here](http://webreflection.github.io/document-register-element/test/) ... do you have any better idea on how to test this everywhere via npm? 'cause testing in every browser is what I've done manually in my intranet befoore pushing this out.

**Comment by opinel** [comment]
After I have made my own built, the `index.html` is still stating that there are "0" tests to run. :-/
In general I would favor to have the tests run against a basic set of local webdrivers by default. So we could assume that phantomjs or webdriver are existing and run the test-suite against them. Whether this would involve a test runner like karma, I don't know.
The second option was to actually make the repository run against a free selenium cluster through TRAVIS CI. There is also the project https://github.com/Ultralight-Elements/ultralight-platform which is already combining dom4 and document-register-element to be run against a SauceLabs stack.

**Comment by WebReflection** [comment]
I love https://github.com/Ultralight-Elements/ultralight-platform
all-in-one solution, so there's nothing to do here? :-)

**Comment by opinel** [comment]
;-) Well, it is not picking up the changes by default. But maybe we should reach out to the author to make it build on dependency changes.

**Comment by WebReflection** [comment]
I've updated the package so that you can `npm run web` and test directly on the localhost link. It does not actually solve the problem but it might be a solution if combined with phantomjs or similar.

**Comment by WebReflection** [comment]
actually, when I've set up [twemoji](https://github.com/twitter/twemoji) tests, I remember telling Travis how to check my stuff through [testrunner file](https://github.com/twitter/twemoji/blob/gh-pages/testrunner.js)

**Comment by WebReflection** [comment]
added phantom js and build system as you can see:
https://github.com/WebReflection/document-register-element#document-register-element

it's passing ^_^

**Comment by opinel** [comment]
Great additions. Thanks.
