### ISSUE TITLE
Problem customizing HTMLImageElement 

### ISSUE THREAD

**Issue by scull06** [WebReflection/document-register-element#131]
I'm trying to customize HTMLImageElement (<img>), below is my code.
There is no error during the execution however, the image is not loaded, but the node was added to the DOM tree. Also, no request to fetch the image was made.
I'm using the version 1.7 in Chrome 62

customElements.define('g-img', class extends HTMLImageElement {
  constructor() {
     super();
    }
}, { extends: 'img' });

let img = document.createElement('g-img', { is: 'img' });
img.src = 'http://path.com/to/my/image.jpg';
document.body.appendChild(img);

**Comment by WebReflection** [comment]
customElements do not support custom builtin extends so I am not planning to fix this because it's not a standard behavior.

Apologies if this is not the answer you were looking for.
