### ISSUE TITLE
Diffs using "this" in Chrome and FF

### ISSUE THREAD

**Issue by albertosantini** [WebReflection/document-register-element#132]
I noticed using `this` a difference behaviour between Chrome (62.x, without polyfill) and Firefox (57,x and 58.x with polyfill).

Adding a property to the node, in FF it seems stripped away.
`this.state` in Chrome is equals to `{}`, while in FF is `undefined`.

Am I missing anything?

``` javascript
class HWelcome extends HTMLElement {
    static get observedAttributes() {
        return ["foo"];
    }

    constructor() {
        super();

        this.innerHTML = "<h1>Hello</h1>";
        this.state = {};
    }

    attributeChangedCallback() {
        console.log(this.state); // Chrome === {}, FF === undefined
    }
}
customElements.define("h-welcome", HWelcome);
```

Live demo: https://plnkr.co/edit/ihXmuso4RSgkDwjJ1IUZ?p=preview

**Comment by WebReflection** [comment]
`const self = super(...args); self.innerHTML = ...`
https://github.com/WebReflection/document-register-element#upgrading-the-constructor-context

**Comment by WebReflection** [comment]
also, how to skip: https://github.com/WebReflection/document-register-element#skipping-the-caveat-through-extends

also, if you use Babel: https://github.com/WebReflection/babel-plugin-transform-builtin-classes

**OR** you could instead: https://github.com/WebReflection/ce-v0 which solves everything
