### ISSUE TITLE
Is the ::slotted() selector supported?

### ISSUE THREAD

**Issue by trusktr** [WebReflection/document-register-element#133]
I haven't tried yet, I don't have a polyfilled env disposable ATM.

If not, is it planned?

**Comment by WebReflection** [comment]
From the [living standard](https://html.spec.whatwg.org/multipage/scripting.html#the-slot-element):

> The slot element defines a slot. It is typically used in a shadow tree. A slot element represents its assigned nodes, if any, and its contents otherwise.

This polyfill has nothing to do with Shadow DOM, which is a different part of the WebComponents specification.

**Comment by trusktr** [comment]
Oops. Wrong place indeed, I posted too fast. Is there a ShadowDOM polyfill that you recommend most?

**Comment by WebReflection** [comment]
> Is there a ShadowDOM polyfill that you recommend most?

It's unpolyfillable, so my best answer is: don't polyfill it.

> I know ShadowDOM is not Custom Elements

maybe other following this repo were not clear about it too
