### ISSUE TITLE
IE11 - disconnectedCallback not fired when nested custom elements are removed using innerHTML property

### ISSUE THREAD

**Issue by php1990** [WebReflection/document-register-element#140]
Found an issue that in IE browser, disconnectedCallback is not fired when nested custom elements are removed from DOM using innerHTML property. Using [removeChild()](https://developer.mozilla.org/de/docs/Web/API/Node/removeChild) before setting a new HTML for an element seems to be the only workaround. 

Added an example here - https://jsfiddle.net/0pc1x186/18/

Expected output (as in FF and Chrome):
<code>element 1 disconnected from DOM! </code>
<code> element 2 disconnected from DOM! </code>

Actual output in IE:
<code>
element 1 disconnected from DOM!
</code>

Found a similar issue in webcomponents too - https://github.com/webcomponents/webcomponentsjs/issues/875

**Comment by WebReflection** [comment]
As far as I can tell you are using innerHTML directly, have you read limitations about that?
https://github.com/WebReflection/document-register-element#using-innerhtml

**Comment by php1990** [comment]
This issue looks similar to https://github.com/WebReflection/document-register-element/issues/101 
Fixing it will solve this issue too.
