### ISSUE TITLE
Change License from MIT to ISC

### ISSUE THREAD

**Issue by WebReflection** [WebReflection/document-register-element#141]
I'm writing this issue to understand if there's any consequence / problem in doing so for whoever bundles this library together with their product.

While MIT is a very common license, the default proposed by `npm` is the [ISC](https://en.wikipedia.org/wiki/ISC_license) one and basically all my most recent software uses such license.

In order to simplify my very own life as developer, where bundling multiple projects of mine means I can just distribute a single LICENSE file, I am willing to move forward with this change unless there are strong arguments about why I shouldn't.

/cc @cramforce

**Comment by cramforce** [comment]
ISC is fine with us. We'd prefer Apache 2.0 if you'd ask :)

**Comment by WebReflection** [comment]
> We'd prefer Apache 2.0 if you'd ask :)

all my most recent projects are under ISC ... changing all of them to Apache 2.0 would not simplify my life, it will actually complicate it and see me stuck for a little while in doing that 😅 

> ISC is fine with us

glad to hear that 🎉

**Comment by MikeVaz** [comment]
We would prefer to keep it as MIT (don't change it). Since changing a license means more work for us like it would need to go through legal approval etc... But unless it is a copyleft license we should be good.

**Comment by WebReflection** [comment]
Sorry @MikeVaz ... you're 4 minutes late.

ISC is basically the equivalent of MIT, it's actually "easier" in wordings and used by OpenBSD too.

If you were OK with MIT, you'd be OK with ISC too.

### ISC in a nutshell
> A permissive license lets people do anything with your code with proper attribution and without warranty. The ISC license is functionally equivalent to the BSD 2-Clause and MIT licenses, removing some language that is no longer necessary.
