### ISSUE TITLE
How about change another way to output "lightercollective" logo message

### ISSUE THREAD

**Issue by xhygithub** [WebReflection/document-register-element#146]
Recently, we have encountered a problem: when we install document-element-registry, we need to execute the lightercollective command, which will visit "https://opencollective.com/hyperhtml/logo.txt" to output the logo text message. But When we visit the url in command line(terminal), it's very slow which will block our process, we spend much time to locate the problem. Can help to prioritize the process?

**Comment by WebReflection** [comment]
the logo is the hyperhtml one though ... nothing to do with this repository, right?

**Comment by WebReflection** [comment]
v1.11 uses a local file

**Comment by WebReflection** [comment]
FYI that is true also for latest hyperHTML

**Comment by xhygithub** [comment]
Thanks for the reply, I just check that v1.11 use a local logo file
