### ISSUE TITLE
Not compatible with vue-web-component-wrapper?

### ISSUE THREAD

**Issue by mrbenshef** [WebReflection/document-register-element#148]
Due to https://github.com/WebReflection/document-register-element/tree/master#v1-caveat this polyfill doesn't work with https://github.com/vuejs/vue-web-component-wrapper.

```javascript
class CustomElement extends HTMLElement {
    constructor () {
        super()
        this.attachShadow({ mode: 'open' })

        const wrapper = this._wrapper = new Vue({
```
(from src/index.js line 81)

Since it does work with https://github.com/webcomponents/webcomponentsjs I was wondering if their is a potential fix.

**Comment by WebReflection** [comment]
As explained in there:
```js
class CustomElement extends HTMLElement {
    constructor () {
        const self = super()
        self.attachShadow({ mode: 'open' })

        const wrapper = self._wrapper = new Vue({
    ...
    return self;
  }
```

Be aware this polyfill doesn't provide Shadow DOM neither, so you might use [attachshadow](https://github.com/WebReflection/attachshadow) or simply stick with webcomponentsjs

**Comment by mrbenshef** [comment]
Yeah that's what I had done but I was trying to avoid forking vue-web-component-wrapper.

Thanks anyway

**Comment by WebReflection** [comment]
> I was trying to avoid forking vue-web-component-wrapper

they are ignoring how `super()` works, which might return a different instance as per specifications.

I'd rather file a bug to their current code than forking it 'cause it won't break anywhere but it will work better in any sort of native constructors patches.

**Comment by WebReflection** [comment]
P.S. the exact fix should be ...
```js
class CustomElement extends HTMLElement {
    constructor (...args) {
        const self = super(...args)
```
