### ISSUE TITLE
ConnectedCallback call sequence

### ISSUE THREAD

**Issue by sbadya** [WebReflection/document-register-element#152]
Hello! Why is ConnectedCallback called async via microtask queue after execution of current code.
In browsers that support the functionality, it's a sync operation.

**Comment by WebReflection** [comment]
to grant the constructor is always called before in browsers that don't support 'em.

**Comment by sbadya** [comment]
> to grant the constructor is always called before in browsers that don't support 'em.

`class WebComponent extends HyperHTMLElement {
   connectedCallback() {
      this.html`<some content></some content>`
  }
}
const webComponent = document.createElement('web-component');
document.body.appendChild(webComponent);
const content = document.querySelector('some content');
`
content isn't available

**Comment by WebReflection** [comment]
that's an anti pattern regardless, and the current behavior of the polyfill won't change ever at this point.

Use HyperHTMLElement if you want to play it safely with the `created` method.

Please also consider this is the most deployed polyfill out there so it won't change in its core at this point.
