### ISSUE TITLE
ReferenceError: module is not defined in browser

### ISSUE THREAD

**Issue by AndyOGo** [WebReflection/document-register-element#155]
If I bundle this with Rollup `module.exports` is not available, hence the browser throughs.

```sh
ReferenceError: module is not defined
```

**Comment by WebReflection** [comment]
how do you call this ?
https://github.com/WebReflection/document-register-element/blob/master/build/document-register-element.node.js#L1508

**Comment by WebReflection** [comment]
Maybe I misunderstood ... is rollup looking for the module or bundling issues?

one seems to be a rollup problem, the other is that you should either avoid bundling this polyfill (or any polyfill in general if not in a polyfill bundle a part) and the other one is that your bundler is incapable of working with CommonJS you should explicitly target `document-register-element/build/https://github.com/WebReflection/document-register-element/blob/master/build/document-register-element.js` file as `require` or `import`.

**Comment by AndyOGo** [comment]
Thanks for your quick feedback.

Correct, Rollup is ESM only.

In general I think it's a good idea to make this module format agnostic, so that AMD, CommonJS or ESM can work with it.

**Comment by AndyOGo** [comment]
May I convince you to reopen this?

**Comment by WebReflection** [comment]
> Correct, Rollup is ESM only.

So, since this is not an ESM module, you either explicitly:

```js
import 'document-register-element/build/document-register-element.js';
```

on top of your file, or you open a bug / edit the title to reflect what is that you are asking: export _dre_ as ESM too.

**Comment by AndyOGo** [comment]
Agreed that is semantically better naming

**Comment by AndyOGo** [comment]
I hope this helps you better and gives you all the data you need #157
