### ISSUE TITLE
Please add ESM module export

### ISSUE THREAD

**Issue by AndyOGo** [WebReflection/document-register-element#156]
I want to import this library with ESnext syntax by as [suggested by readme](https://github.com/WebReflection/document-register-element#how) and bundle it all up with rollup:

```js
import 'document-register-element'; // ES2015
```

Please specify the defacto standard [`module` property for esm exports](https://github.com/nodejs/node-eps/blob/4217dca299d89c8c18ac44c878b5fe9581974ef3/002-es6-modules.md#51-determining-if-source-is-an-es-module) within `package.json`

[Rollup](https://rollupjs.org/guide/en) is an ESM-only module bundler in contrast to e.g. Webpack. Unfortunately the resulting Rollup build throws:

```sh
ReferenceError: module is not defined
ReferenceError: global is not defined
```

**Comment by WebReflection** [comment]
`1.12.0` is out and it should work as ESM. Please let me know if that is not the case.

**Comment by AndyOGo** [comment]
wau, great that was really quick. I will just test it.

Thanks you a lot
