### ISSUE TITLE
Built-in elements don't work in Firefox

### ISSUE THREAD

**Issue by gkubisa** [WebReflection/document-register-element#158]
Here's what happens:

1. Custom Elements V0 are not implemented in Firefox, so [V0 is polyfilled](https://github.com/WebReflection/document-register-element/blob/aa65b7dd77b33a2639978650fe839df0b85dc6fd/src/document-register-element.js#L301).
2. As part of the V0 polyfill, [`createElement` is patched](https://github.com/WebReflection/document-register-element/blob/aa65b7dd77b33a2639978650fe839df0b85dc6fd/src/document-register-element.js#L627).
3. The patch uses the `secondArgument` function to [prepare the second argument](https://github.com/WebReflection/document-register-element/blob/aa65b7dd77b33a2639978650fe839df0b85dc6fd/src/document-register-element.js#L631) for `createElement`. Some browsers allow the second argument to be a string but Firefox requires `{ is: '...' }`.
4. The polyfill tries to [replace the `secondArgument` function](https://github.com/WebReflection/document-register-element/blob/aa65b7dd77b33a2639978650fe839df0b85dc6fd/src/document-register-element.js#L1067-L1069) with one that works in Firefox.
5. Unfortunately, the `secondArgument` function is not replaced because [`createElement` does not throw](https://github.com/WebReflection/document-register-element/blob/aa65b7dd77b33a2639978650fe839df0b85dc6fd/src/document-register-element.js#L1065) when called with a string as the second argument. Even though it does not throw, it does not produce a customized built-in element either.

I think the fix is to check `outerHTML` of [the test element](https://github.com/WebReflection/document-register-element/blob/aa65b7dd77b33a2639978650fe839df0b85dc6fd/src/document-register-element.js#L1065) to see if it contains the `is` attribute, and throw an error, if not. This would cause the `catch` to execute and replace the `secondArgument` function with one that works.

I think we might get the same problem in Chrome once Custom Elements V0 are removed from that browser - they are currently deprecated.

Are there any plans to remove support for Custom Elements V0 from this polyfill, considering that browsers are already dropping it?

**Comment by WebReflection** [comment]
> Are there any plans to remove support for Custom Elements V0 from this polyfill, considering that browsers are already dropping it?

No, but you shouldn't care. V0 is battle tested and used to bring built ins to V1 capable browsers.

Firefox has also been tested extensively, so unless you tell me which version you are using, it's hard for me to do anything here.

The `outerHTML` trick you mentioned is used in built-in-element which patches only built-in extends for non capable browsers: https://github.com/WebReflection/built-in-element

If you want to use V1 built-in elements, I strongly suggest you use that polyfill instead.

The way you'd go for it is described in the Medium post, summarized as:

```html
<script>
if (!this.customElements)
  document.write('<script src="//unpkg.com/document-register-element"><\x2fscript>');
</script>
```

You can test the live page there: https://webreflection.github.io/built-in-element/test/es5/

**Comment by gkubisa** [comment]
Sorry, I should have mentioned the version... it's Firefox 63.0 (64-bit) on Ubuntu 16.04.

I still need to support IE11, so I believe https://github.com/WebReflection/built-in-element would not be enough and I have to use https://github.com/WebReflection/document-register-element.

**Comment by gkubisa** [comment]
I've just created this jsfiddle to demonstrate the problem: https://jsfiddle.net/0dm72zv6/4/. It works fine in Chrome but fails in Firefox 63. If I remove document-register-element, it works in Firefox too.

**Comment by WebReflection** [comment]
> I still need to support IE11

IE doesn't have `customElements` so that script tag on top of any of your page would work for IE11 (and many others).

> If I remove document-register-element, it works in Firefox too.

That means you shouldn't use DRE in the first place.

I'll try to have a look what is wrong or how I can improve but it seems like you are giving DRE to browsers that shouldn't need it.

Anyway, worth investigating.

**Comment by WebReflection** [comment]
So, `v1.13.0` is out, and I've also added a [how to migrate to V1](https://github.com/WebReflection/document-register-element#important-how-to-migrate-to-native-v1) with hopefully all the details in (already spotted few typos though, on it already)
