### ISSUE TITLE
TypeError: new.target does not define a custom element

### ISSUE THREAD

**Issue by kapouer** [WebReflection/document-register-element#159]
Browser: epiphany 3.30 / webkitgtk 2.22.3 which is a bit like safari w.r.t. custom elements.
After upgrading from 1.11.0 to 1.13.1, the message in the title appears at that point:
```
class HTMLCustomElement extends HTMLElement {
	constructor(me) {
		me = super(me); /* HERE */
		me.init();
		return me;
	}
	init() {}
}

class HTMLElementTemplate extends HTMLCustomElement {
  init() {

  }
  connectedCallback() {

  }
  //.....
}
```

**Comment by WebReflection** [comment]
try with:
```js
constructor(...args) {
  const self = super(...args);
  self.init();
  return self;
}
```

Alternatively, please follow latest description on how to bring Custom Elements with built-in extends to every browser.

https://github.com/WebReflection/document-register-element#important-how-to-migrate-to-native-v1

**Comment by WebReflection** [comment]
yet, both suggestions are more than valid. Don't polyfill browsers that don't need it.
