### ISSUE TITLE
document.registerElement is deprecated and will be removed in M73

### ISSUE THREAD

**Issue by wdanda** [WebReflection/document-register-element#160]
Version: 1.13.1

Warning message: "[Deprecation] document.registerElement is deprecated and will be removed in M73, around March 2019. Please use window.customElements.define instead. See https://www.chromestatus.com/features/4642138092470272 for more details."

Is this a known bug?

**Comment by WebReflection** [comment]
which bug? ... it's a deprecation warning, use `customElements.define()` ... which is V1.

It's all here: https://github.com/WebReflection/document-register-element#important-how-to-migrate-to-native-v1

**Comment by AtomicNoggin** [comment]
I think the question is, will existing code written to the V0 spec still run once  document.registerElement disappears in Chrome

**Comment by WebReflection** [comment]
@AtomicNoggin do you have an issue in canary?

Anyway, I suggest **everyone** to move to V1 ASAP. This polyfill is basically death already. If you want to support your users, move to V1.

Closing this as there's nothing else to discuss.
