### ISSUE TITLE
Post-install script slowness

### ISSUE THREAD

**Issue by melxx001** [WebReflection/document-register-element#162]
Hello... Thanks for the great package. 

I noticed that there's a call to the `lightercollective` package in the post-install stage that goes and tries to get a logo. In our Capital One CI environment (behind proxies and using Docker), it increases the build time by ~2 minutes.

![image](https://user-images.githubusercontent.com/6652886/50523448-30b83580-0a9e-11e9-869b-661748a951d5.png)

Instead of `lightercollective`, perhaps you could use `opencollective postinstall` which I've seen completes much faster?

![image](https://user-images.githubusercontent.com/6652886/50523505-812f9300-0a9e-11e9-9ee5-e475aeaf5274.png)

**Comment by WebReflection** [comment]
that doesn't sound right ... which version of DRE are you using? The current one, since quite a while, has `logo.txt` file that is used by lightercollective so, since whatever change I need to make requires you to update your DRE version, how about you update it already and see the issue vanish?

**Comment by melxx001** [comment]
We have it at `1.8.1`. 

I'll message the team to have them upgrade. Thanks for the info.

**Comment by WebReflection** [comment]
after 7 days of silence I guess there's nothing to do here for me.
