### ISSUE TITLE
Multiple instances of the polyfill leads to unexpected behaviour

### ISSUE THREAD

**Issue by dnicolson** [WebReflection/document-register-element#173]
I am trying to include the latest version of the polyfill and there is a possibility of an existing version (0.5.4) already included inlined in the page that might not be able to be removed. The two versions seem to work and with `window.customElements.define` being polyfilled for older browsers and not for native implementations.

I noticed that if you include the latest version of the polyfill it leads to strange behaviour, after it is included the second time the following (caught) exception occurs:

`DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "document-register-element-a" has already been used with this registry`

And the second time:

`DOMException: Failed to execute 'registerElement' on 'Document': Registration failed for type 'document-register-element-a'. A type with that name is already registered.`

How is performance affected if `window.customElements` is polyfilled for modern browsers?

**Comment by WebReflection** [comment]
Latest patch fixes this 👋
