### ISSUE TITLE
[QUESTION] Unable to get property '_isMounted' of undefiened.

### ISSUE THREAD

**Issue by supproduction** [WebReflection/document-register-element#179]
After connection your plugin to my custom elements (`custom-component-wrapper` plugin)  based on vue I have next issue.
Have you faced with this problem? Actually I can't totally understant what is this?
![image](https://user-images.githubusercontent.com/16482929/70187815-cb31e780-16f7-11ea-9a6d-8ed0cfb297e1.png)

**Comment by WebReflection** [comment]
no idea what's even `_isMounted`, so I am closing this until it follows these steps:
https://medium.com/@WebReflection/how-to-file-a-github-lab-issue-7080b8c0cef5
