### ISSUE TITLE
Polyfill does not seem to be working in IE 11 

### ISSUE THREAD

**Issue by redfellow** [WebReflection/document-register-element#182]
I have this in my `<head>`:

```js
<script>this.customElements||document.write('<script src="//unpkg.com/document-register-element"><\x2fscript>');</script>
<script src="//unpkg.com/@ungap/custom-elements-builtin"></script>
```
Yet attempting to extend a class in IE11 (which I'm attempting to customElement.define afterwards) fails. At this point I expect to be understanding something very wrong, so any input would be greatly appreciated.

![image](https://user-images.githubusercontent.com/1110164/88422163-7364ff80-cdf2-11ea-803b-59dd0372e898.png)

**Comment by WebReflection** [comment]
IE11 doesn't support `class`

**Comment by redfellow** [comment]
Oh, never ventured there since I've been only coding in vanilla for years. I'll look into how to do that, or if possible, code directly in a supported syntax/format.

Thank you.

**Comment by WebReflection** [comment]
> or if possible, code directly in a supported syntax/format.

you don't want to do that ... use babel to transpile your code 😉

**Comment by redfellow** [comment]
Let's just say that I'm working with somewhat perverted legacy in-house framework that's been built for the past 20 years.

I don't know much 'bout Babel, but it's very difficult to get any preprocessors in there. 😓 But I'm gonna look into it on monday and see what's what.

**Comment by WebReflection** [comment]
If you can't get any preprocessor in there, you can forget about class, or anything related to modern JavaScript, as nothing will work in your target browsers

**Comment by WebReflection** [comment]
to expand, there's literally nothing I cna do in here to make `class` or anything modern work in IE11, so this is your only chance https://babeljs.io/
