### ISSUE TITLE
We unable to install latest version @1.14.7

### ISSUE THREAD

**Issue by pvasantha** [WebReflection/document-register-element#185]
internal/modules/cjs/loader.js:638
    throw err;
    ^
Error: Cannot find module '*****node_modules\document-register-element\node_modules\.bin\lightercollective'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} 
(current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} 
(current: {"os":"win32","arch":"x64"})

Look like it is not downloading the dependent module
could anyone help here

**Comment by WebReflection** [comment]
is this new? are you on windows? was it working 'till yesterday?

**Comment by WebReflection** [comment]
Could you please tell me if latest version fixed this?

**Comment by pvasantha** [comment]
No. It is not fixing it. It was working until yesterday..

> document-register-element@1.14.9 postinstall ********node_modules\document-register-element
> node "$(npm bin)/lightercollective"

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '****************node_modules\document-register-element\$(npm bin)\lightercollective'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\webpack-dev-server\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} 
(current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} 
(current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! document-register-element@1.14.9 postinstall: `node "$(npm bin)/lightercollective"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the document-register-element@1.14.9 postinstall script.

**Comment by LeovR** [comment]
We are also experiencing the same issue.
On Windows it is not possible to execute `$(npm bin)`.

**Comment by eiszfuchs** [comment]
Installing `1.14.9` failed on Linux, too. I'm also using `fish` as shell, where `$(npm bin)` also isn't valid syntax.

**Comment by WebReflection** [comment]
I like the fact a merge request to solve non executable OS turned out revealing how much of a mess is to write an *npm* instruction ... but as this module is basically deprecated, since [@ungap/custom-elements](https://github.com/ungap/custom-elements#readme) is what everyone should use instead, I might as well remove the dependency and call it a day.

**Comment by WebReflection** [comment]
dear all, *ligthercollective* is gone, nobody should ever have issues anymore with it
