### ISSUE TITLE
Script repeated

### ISSUE THREAD

**Issue by dethe** [WebReflection/document-register-element#19]
In `examples/base.html` this line:

```
<script src="//cdnjs.cloudflare.com/ajax/libs/es5-shim/4.1.0/es5-shim.js"></script>
```

Is repeated twice, character for character. Is that intentional to work around some IE8 weirdness (I spent enough years hacking on IE4+ to believe that) or a bug?

**Comment by WebReflection** [comment]
look closer ...
```html
      <script src="//cdnjs.cloudflare.com/ajax/libs/es5-shim/4.1.0/es5-shim.js"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/es5-shim/4.1.0/es5-sham.js"></script>
```
sham is after shim

**Comment by dethe** [comment]
Ha ha! OK, that was too subtle for me. Good name, though. Thanks!

**Comment by WebReflection** [comment]
I haven't chosen those names but thanks!
