### ISSUE TITLE
IE 10 - Problem with the "MutationObserver" workaround

### ISSUE THREAD

**Issue by matias91** [WebReflection/document-register-element#20]
Hi.

I've been having a problem with IE 10 when i create a custom element and, in the postRender, i try to move another custom element inside the first one. Because the "DOMNodeInserted" is triggered and the cycle of the "onDOMNode" begins. The child element starts the createdCallback but when is appended isn't rendered.

For example:

/* This is called inside the cycle of the createdCallback */
postRender: function() {

    var contentEl = this.querySelector('.parent-content'),
        child = this.querySelector('.child'),
        item,
        i = 0;

    while (child.children.length > 0) {
          item = child.children[0];
          contentEl.appendChild(item);
    }
}

The "item" appended is a custom element but it's shown without rendering.
In the browsers that support  the "MutationObserver" this works fine.

I've been searching but can't find a solution. Someone else can reproduce it?

**Comment by WebReflection** [comment]
can you please provide a basic page to test? I don;'t know what is postRender, I don't know where are those elements, and I actually don't understand what you are trying to do because to me it looks like you are re-appending to the same container same elements that where already there.

Thanks for helping figuring out this one (also, IE10 which one? where?)

**Comment by WebReflection** [comment]
@matias91 can you please provide a basic test or even test with latest and tell me if there's still a problem?

**Comment by WebReflection** [comment]
closing until I have a proper bug to work on.

**Comment by matias91** [comment]
Sorry, @WebReflection, i was busy.
The problem we have is when we try to move (append, remove) elements that are not rendered.
We found that the problem is in the polyfill of the mutationObserver in IE 10.
If the browser doesn't support  mutationObserver, you attach two events:
 document.addEventListener('DOMNodeInserted', onDOMNode(ATTACHED));
 document.addEventListener('DOMNodeRemoved', onDOMNode(DETACHED));

This doesn't emulate the full behavior of the mutationObserver.
So, when a element is attached or detached the "createdCallback" is triggered.
We fixed this adding a polyfill for the IE 10 mutationObserver.

Sorry for the delay.
Regards.

**Comment by WebReflection** [comment]
> So, when a element is attached or detached the "createdCallback" is triggered.

this makes little sense to me ... the createdCallback is invoked only once per node lifecycle. This can trigger at any time and might be asyncronous, but it should be triggered as node setup before anything else (and always before the attachedCallback)

I really would like to have a basic page example to test the problem, but I'd also wouldn't mind a link to such MutationObserver polyfill you used so that others might use it as similar solution if needed.

Thanks.

**Comment by matias91** [comment]
Yes, you are right, the createdCallback is always invoked once. But in our case the problem is "when" is invoked, because we are appending a custom element (childNode) inside the createdCallback lifecycle of another custom element (parentNode), this starts the createdCallback of the childNode when the cycle of the parent didn't finish. This flow doesn't happen in the browsers that support mutationobserver.

I will try to make an example later, because i'm at work now.
This is the link of the polyfill:
https://github.com/megawac/MutationObserver.js/blob/master/MutationObserver.js

Thanks!

**Comment by WebReflection** [comment]
> this starts the createdCallback of the childNode when the cycle of the parent didn't finish. This flow doesn't happen in the browsers that support mutationobserver.

OK, this makes more sense ... yes, MutationObserver are indeed asynchronous so this case shouldn't happen. I see if I can debounce the creation somehow in code, reopening for now.

**Comment by WebReflection** [comment]
@matias91 do you mind testing [one of the latest build files](https://github.com/WebReflection/document-register-element/tree/master/build) removing that polyfill and tell me if everything is fine now?

I should have made the invocation asynchronous which is similar to what MutationObserver does ... I don't mind using that poly upfront, when and if needed, but it looks/feel a very greedy solution that won't probably scale with huge documents.

Thank you

**Comment by matias91** [comment]
@WebReflection, all works great now!

IE 10 follows the correct flow. Thanks for the patience and for the support!
Now we don't need to use another polyfill.

Thanks a lot!

**Comment by WebReflection** [comment]
thank you for the report. This has been flagged as `0.4.0` and will be hopefully soon available in the CDN.
