### ISSUE TITLE
Failed to execute 'registerElement' on 'Document': Registration failed for type 'counter'. The type name is invalid.

### ISSUE THREAD

**Issue by ruben1** [WebReflection/document-register-element#25]
I have this error when using this polyfill. The thing this error appears when using some names when registering them. Is there any restriction on naming of components that I'm not aware? It must be something silly but just in case..
Ex: Registering a component with name 'counter' gives me the error. However, using 'counter-component' is ok. 

I'll will push my code later. 
Trying to figure out the error for now...

**Comment by ruben1** [comment]
Here's my code

https://github.com/ruben1/Timer-Component/blob/master/counter.js

It works when changing the name, but not with 'counter'

**Comment by WebReflection** [comment]
it's a native error, not a polyfill one ... even without this poly in:
```
Uncaught DOMException: Failed to execute 'registerElement' on 'Document': Registration failed for type 'counter'. The type name is invalid.(anonymous function) @ VM55:48(anonymous function) @ VM55:51InjectedScript._evaluateOn @ VM34:883InjectedScript._evaluateAndWrap @ VM34:816InjectedScript.evaluate @ VM34:682
```

Rule number 1 about custom elements: use a dash in the name!

This is future proof (you don't conflict with W3C or WHATWG if they decide to promote a `counter` element) and a less obtrusive practice overall.

**Comment by ruben1** [comment]
Got it! Thanks @WebReflection
