### ISSUE TITLE
Exclude examples from NPM package

### ISSUE THREAD

**Issue by thomaswilburn** [WebReflection/document-register-element#26]
Currently if I install this shim from NPM, it comes with ~108MB of examples, which I would imagine most people don't use. We use this shim a lot at the Seattle Times, and although hard drives are fairly large these days, it does add up. Of course, you've already got a .npmignore file here--could you add examples/* to it, to cut down on the weight and speed up our install times?

**Comment by WebReflection** [comment]
published as `0.4.2` apologies for any inconvenient. Please close this if current npm without examples is fine, thank you.

**Comment by thomaswilburn** [comment]
Perfect, thanks!
