### ISSUE TITLE
`createdCallback` no longer invoked after 0.3.5

### ISSUE THREAD

**Issue by tjvantoll** [WebReflection/document-register-element#28]
Hey @WebReflection,

I went to update your polyfill from 0.3.0 and noticed that my [clock face demo](http://jsfiddle.net/tj_vantoll/gnf2j/) no longer works in non-Chrome browsers. I tracked the issue down to the 0.3.5 release (as it works fine with 0.3.4), and it seems to be [this commit](https://github.com/WebReflection/document-register-element/commit/dfc5a8679ddf938a98b7b67a4019da75b97ede39).

Any idea what's up here? My example works fine in Chrome, and it also works fine if I use Google's polyfill. I might try to dig into the code later, but for now I thought I'd create this as an fyi.

Thanks.

**Comment by WebReflection** [comment]
`0.4.3` please, sorry for the inconvenient. You just got a version that was screwed via `innerHTML` helper :-(

**Comment by WebReflection** [comment]
to be precise: `0.3.0` was OK, between `0.3.1` and `0.4.2` elements already on DOM were not properly initialized, only those created via `createElement`.

This has been just fixed thanks to an unrelated bug that revealed the typo/gotcha.

Again my deepest apologies for the inconvenient, now I have also a test for that too.

**Comment by WebReflection** [comment]
P.S. for JS fiddle you need to wait CDNJS to purge the latest `0.4.3` file

**Comment by tjvantoll** [comment]
All is working for me with 0.4.3 :+1: Thanks for the quick response!
