### ISSUE TITLE
Unable to run mocha/phantomjs with AMD version of document-register-element

### ISSUE THREAD

**Issue by lelong71** [WebReflection/document-register-element#30]
I used grunt-mocha to test my custom element and it fails due to "Warning: ReferenceError: Can't find variable: REGISTER_ELEMENT" when using AMD version of document-register-element.amd.js

I need to add the following to the script to avoid the issue:

var REGISTER_ELEMENT = 'registerElement';
if (REGISTER_ELEMENT in document) {
  return;
}

**Comment by WebReflection** [comment]
oops, should be fixed with version `0.4.4`

Thanks for the report, feel free to close if 0.4.4 solves. Cheers

**Comment by WebReflection** [comment]
ok, I'll close for ya ^_^
