### ISSUE TITLE
ie8 test error

### ISSUE THREAD

**Issue by shelwinjue** [WebReflection/document-register-element#31]
test in ie8 there is an error,The test not passed
![image](https://cloud.githubusercontent.com/assets/6322676/8302571/f4552346-19c9-11e5-9c36-486a8f4c1e44.png)

**Comment by WebReflection** [comment]
there's a good chance I've forgotten to update the test page live, will double check soon. Thanks

**Comment by WebReflection** [comment]
yeah, UglifyJS apparently had a lot of fun dropping reserved words parsing ... I am trying to figure out how to fix this. Apologies for any inconvenient.

**Comment by WebReflection** [comment]
OK, `0.4.5` just pushed should be just fine. `innerHTML` has some nasty test plus UglifyJS wasn't wrapping words such `extends` so yeah, it was a proper mess.

Apologies 'cause I wish I could easily spawn IE8 per each build but it's not that simple right now.

Please feel free to close once double checked.

**Comment by shelwinjue** [comment]
Thanks!
