### ISSUE TITLE
Can i defer registration of an element?

### ISSUE THREAD

**Issue by marcog83** [WebReflection/document-register-element#38]
Hi, I love custom elements and this project that allow us to support they even in ie8 :)
I'd like to know if i can write my custom markup first and then register all my custom elements. 
For instance, loading a ```<script async>``` tag at the bottom of the page where my elements will be registered.

Thanks 
Marco

**Comment by WebReflection** [comment]
Please note this is a polyfill, whatever question you have will most likely find answers in the specification. 

Anyway, to quickly answer: yes, this is for example already what AMP project is doing, using CustomElements that are defined lazily through an async script. https://www.ampproject.org/

Regards

**Comment by marcog83** [comment]
Thanks a lot. This answer convinced me going deeper about custom elements.
