### ISSUE TITLE
IE8 errors when running the x-clock example with latest sources of ie8.js and dom4.js

### ISSUE THREAD

**Issue by obihill** [WebReflection/document-register-element#39]
Thanks a lot for this library; it's really made life easier when trying to build cross-browser web components.

I have a specific issue when I run your x-clock example using recent sources of ie8.js (0.2.9), dom4.js (1.5.1), and document-register-element.js (0.5.0). On IE8, I get the following errors:

![Error Message](https://www.dropbox.com/s/mnmq60gm30m9v3j/github_webreflection_documentregisterelement_issue_001.png?raw=1)

Here is the HTML code:

```html
<!DOCTYPE html>
<html>
<head>
    <title>x-clock</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0,minimal-ui">
    <!--[if lte IE 9]><script>(function(f){window.setTimeout=f(window.setTimeout);window.setInterval=f(window.setInterval)})(function(f){return function(c,t){var a=[].slice.call(arguments,2);return f(function(){c.apply(this,a)},t)}});</script><![endif]-->
    <!--[if IE 8]><script src="//cdnjs.cloudflare.com/ajax/libs/ie8/0.2.9/ie8.js"></script><![endif]-->
    <script src="//cdnjs.cloudflare.com/ajax/libs/dom4/1.5.1/dom4.js"></script>
    <!--[if IE 8]><script src="//cdnjs.cloudflare.com/ajax/libs/document-register-element/0.3.0/dre-ie8-upfront-fix.js"></script><![endif]-->
    <script src="//cdnjs.cloudflare.com/ajax/libs/document-register-element/0.5.0/document-register-element.js"></script>
    <!--[if IE 8]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/es5-shim/4.1.0/es5-shim.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/es5-shim/4.1.0/es5-sham.js"></script>
    <![endif]-->
    <script src="js/restyle.js"></script>
    <!-- x-clock Custom Element -->
    <script src="js/x-clock.js"></script>
</head>
<body>
<h3>dynamic</h3>
<x-clock>10:10:30</x-clock>
<h3>fixed</h3>
<x-clock hour="10" minute="10" second="30">10:10:30</x-clock>
</body>
</html>
```

Any way to fix this?

**Comment by WebReflection** [comment]
I'm afraid there was a problem in latest DOM4 ... curios fact: IE8 already had `contains` in its `Element` prototype, but IE8 doesn't know about `Node`.

The x-clock demo is not suitable for IE8 in any case because it uses CSS properties IE8 doesn't know.  The demo  you are looking for is probably [the map one](http://webreflection.github.io/document-register-element/test/examples/x-map.html) which will  work as soon  as CDNJS will update the version `1.5.2` I've pushed few minutes ago. It could take a couple of days.

Best regards

**Comment by obihill** [comment]
Thanks a lot.

I'm aware that the Clock example doesn't work on IE8; I was actually using the code cadence of the example [for IE8 compatibility] and noticed that it works with the old sources but not with the newer updated ones. All fixed now after your update.

Cheers.
