### ISSUE TITLE
`target.getAttribute` is not defined

### ISSUE THREAD

**Issue by calebmer** [WebReflection/document-register-element#40]
Even with some of the simplest components, I keep getting the following error (paraphrase from Firefox console although it seems to happen in all browsers):
```
TypeError: target.getAttribute is not a function
getTypeIndex()                document-register-element.max.js:422
verifyAndSetupAndAction()     document-register-element.max.js:520
loopAndVerify()               document-register-element.max.js:397
onReadyStateChange()          document-register-element.max.js:469
```

The following is a sample of my component:
```js
let Star = document.registerElement('x-star', {
  prototype: {
    createdCallback() {
      console.log('created')
    },
    attachedCallback() {
      console.log('attached')
    }
  }
})
```

**Comment by WebReflection** [comment]
Other frameworks/library involved? Cause AFAIK your basic example is tested
and works pretty much everywhere,  not sure I can do much in here

**Comment by WebReflection** [comment]
this page works as expected:  http://webreflection.github.io/document-register-element/test/examples/x-star.html

Bear in mind it's full of obtrusive frameworks out there, these might not play that well with polyfilled **standards** .
