### ISSUE TITLE
Custom element won't render in nested element under IE8.

### ISSUE THREAD

**Issue by windyGex** [WebReflection/document-register-element#42]
Look at the following code, 123456 will be displayed in other browser but IE8,
IE8 only show 123，`a-item` element does not render. What should I do?

```javascript
document.registerElement(
    'a-item',
    {
        prototype: Object.create(
            HTMLElement.prototype,
            {
                createdCallback: {value: function () {
                    this.innerText = this.getAttribute('name');
                }}
            }
        )
    }
);

document.registerElement(
    'a-list',
    {
        prototype: Object.create(
            HTMLElement.prototype,
            {
                createdCallback: {value: function () {
                    this.innerHTML = '123<a-item name=456></a-item>';
                }}
            }
        )
    }
);

var a = document.createElement('a-list')
document.body.appendChild(a);
```

**Comment by WebReflection** [comment]
innerHTML  requires a special file ... have you included it?
https://github.com/WebReflection/document-register-element#using-innerhtml

**Comment by windyGex** [comment]
Yes,I has include it,should I use innerHTML instead of element.innerHTML?

**Comment by WebReflection** [comment]
that would be my first hint, the second one:

```js
var a = document.createElement('a-item');
a.name = '456';
this.append('123', a);
```

the `.append` method comes from DOM4 https://github.com/WebReflection/dom4/#dom4

**Comment by windyGex** [comment]
Actually, I want to use element.innerHTML method creating dom.Can you support it or what should I do ?

**Comment by WebReflection** [comment]
if you read this https://github.com/WebReflection/document-register-element#using-innerhtml
and the bug related https://github.com/WebReflection/document-register-element/issues/21
you realize that I won't support that within the polyfill, but I am supporting it already through the helper script: https://github.com/WebReflection/document-register-element/blob/master/build/innerHTML.max.js


Your code should look like the following:
```js

var innerHTML = innerHTML || document.registerElement.innerHTML;

document.registerElement(
    'a-item',
    {
        prototype: Object.create(
            HTMLElement.prototype,
            {
                createdCallback: {value: function () {
                    this.innerText = this.getAttribute('name');
                }}
            }
        )
    }
);

document.registerElement(
    'a-list',
    {
        prototype: Object.create(
            HTMLElement.prototype,
            {
                createdCallback: {value: function () {
                    // this is the main difference
                    innerHTML(this, '123<a-item name=456></a-item>');
                }}
            }
        )
    }
);

var a = document.createElement('a-list')
document.body.appendChild(a);
```

If you don't have the `innerHTML` available it means you are not including it instantly after this polyfill, but you should.

This is an example on how you should include bits and bops
https://github.com/WebReflection/document-register-element/blob/master/index.html#L9-L14

Be sure every version of each script points to the latest/right file.

I am going to close this. Let me know how that went.

**Comment by windyGex** [comment]
ok, I try to run your code, but it can't render under IE8 too.

* innerHTML's way

   It won't render
* append's way

   It will be render as `123null`

The following is my full code.

```html
<!DOCTYPE html>
<html>
    <head>
        <title>document-register-element test</title>
        <meta http-equiv="content-language" content="en-US"/>
        <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no"/>
        <meta name="apple-mobile-web-app-capable" content="yes"/>
        <meta names="apple-mobile-web-app-status-bar-style" content="black"/>
        <!--[if lte IE 9]><script>(function(f){window.setTimeout=f(window.setTimeout);window.setInterval=f(window.setInterval)})(function(f){return function(c,t){var a=[].slice.call(arguments,2);return f(function(){c.apply(this,a)},t)}});</script><![endif]-->
        <!--[if IE 8]><script src="http://cdnjs.cloudflare.com/ajax/libs/ie8/0.2.3/ie8.js"></script><![endif]-->
        <script src="http://cdnjs.cloudflare.com/ajax/libs/dom4/1.4.5/dom4.js"></script>
        <!--[if IE 8]><script src="build/dre-ie8-upfront-fix.js"></script><![endif]-->
        <script src="build/document-register-element.max.js"></script>
        <script src="build/innerHTML.max.js"></script>
        <!--[if IE 8]>
     <script src="//cdnjs.cloudflare.com/ajax/libs/es5-shim/4.1.0/es5-shim.js"></script>
     <script src="//cdnjs.cloudflare.com/ajax/libs/es5-shim/4.1.0/es5-sham.js"></script>
   <![endif]-->
    </head>
    <body>
      <script>
      document.registerElement(
    'a-item',
    {
        prototype: Object.create(
            HTMLElement.prototype,
            {
                createdCallback: {value: function () {
                    this.innerText = this.getAttribute('name');
                }}
            }
        )
    }
);

document.registerElement(
    'a-list',
    {
        prototype: Object.create(
            HTMLElement.prototype,
            {
                createdCallback: {value: function () {
                    // this is the main difference
                    innerHTML(this, '123<a-item name=456></a-item>');
                    // var a = document.createElement('a-item');
                    // a.setAttribute('name', '456');
                    // this.append('123', a);
                }}
            }
        )
    }
);

var a = document.createElement('a-list')
document.body.appendChild(a);
      </script>
    </body>
```html

**Comment by WebReflection** [comment]
what happen if you move that part after onload?
```js
this.onload = function () {
  var a = document.createElement('a-list');
  document.body.appendChild(a);
};
```
Maybe there is some asynchronous initialization problem.

In any case, bear in mind support for IE8 is experimental. There might be hiccups

**Comment by windyGex** [comment]
The same result.May be it's not `onload` reason. I find the problem, asynchronous reminds me.

I try to use append's way,and make createdCallback asynchronous, it works.

```js
document.registerElement(
    'a-item',
    {
        prototype: Object.create(
            HTMLElement.prototype,
            {
                createdCallback: {value: function () {
                    setTimeout(function(){
                       this.innerText = this.getAttribute('name');
                    }.bind(this), 10);
                }}
            }
        )
    }
);
```

so I think should make createdCallback asynchronous under IE8, I try to modify code at https://github.com/WebReflection/document-register-element/blob/master/src/document-register-element.js#L471-L472

```js
if(IE8){
      setTimeout(function(){
        node.createdCallback();
        node.created = false;
      },10);
    }else{
      node.createdCallback();
      node.created = false;
     }
```
well, it works any way, even I use element.innerHTML.(Just create it before append DOM)

Thanks.

**Comment by WebReflection** [comment]
unfortunately making it always asynchronous breaks every other test so it's not an option.

I will think about it, meanwhile it's good there is a bug to point at. I am going also to keep this close for now as won't fix, I might eventually update it or reopen it whenever I'll find time to dig into why on earth IE8 is again causing troubles.

Apologies if this solution is not ideal but the support for IE8 is very edge-case and experimental, I can't make this right now a priority for me (zero time)
