### ISSUE TITLE
ie8 purge() maybe have a bug when detached more than one Element?

### ISSUE THREAD

**Issue by acelan86** [WebReflection/document-register-element#45]
```javascript
function purge() {
  for (var
    node,
    i = 0,
    length = targets.length;
    i < length; i++
  ) {
    node = targets[i];
    if (!documentElement.contains(node)) {
      targets.splice(i, 1);
      verifyAndSetupAndAction(node, DETACHED);
    }
  }
}
```
if targets.length bigger than 1, when  `targets.splice(i, 1);`  targets.length is change,  then `node = targets[i]` will  be `undefined` ,   so `documentElement.contains(node)`  will throw a error

**Comment by acelan86** [comment]
fix by:
```javascript
function purge() {
  for (var
    node,
    restTargets = [],
    i = 0,
    length = targets.length;
    i < length; i++
  ) {
    node = targets[i];
    if (!documentElement.contains(node)) {
      verifyAndSetupAndAction(node, DETACHED);
    } else {
      restTargets.push(node);
    }
  }
  targets = restTargets;
}
```
or better?

**Comment by WebReflection** [comment]
There are tests in place. Does this pas all current tests? Can you write down an example where you explain what you are trying to fix and how your code fixes that?

I am having hard time following your issues ...

**Comment by WebReflection** [comment]
Also, and once again, IE8 is experimental. I'm not sure anything is going to be fixed 'cause this repository is already widely deployed in production. Not sure I'm going to risks these kind of untested changes to fix IE8, thanks for your understanding.

**Comment by acelan86** [comment]
Thank u, IE8 is need to consider in China  ;(
i will fill my test case for this issue tomorrow

**Comment by acelan86** [comment]
https://github.com/WebReflection/document-register-element/pull/46/files
