### ISSUE TITLE
dre-ie8-upfront-fix enumerable error

### ISSUE THREAD

**Issue by pweiss-mri** [WebReflection/document-register-element#49]
I'm getting the error **'enumerable' attribute on the property descriptor cannot be set to 'true' on this object** when running wrapSetter() on 'textContent' in IE8.

In the max version of the file this is on line 64:

```javascript
defineProperty(ElementPrototype, name, substitute);
```

**Comment by WebReflection** [comment]
AFAIK [tests passes](http://webreflection.github.io/document-register-element/test/) on IE8 so these info are not enough.

**Comment by pweiss-mri** [comment]
You're right, they are passing for me too in the same browser.  Must by an issue with what I'm doing.
