### ISSUE TITLE
Issue in IE8.JS not able to load component

### ISSUE THREAD

**Issue by uppalapati41** [WebReflection/document-register-element#56]
Hello,

          In IE8.js file getting script error which is not loading element in IE8. Referred sample clock example [http://webreflection.github.io/document-register-element/test/examples/x-clock.html]. Can some one please help out with this.

Thanks.

**Comment by WebReflection** [comment]
in order to consider this bug I need a test example with source code and also a better formatted MD.

I'll close this for now, please open a better bug report, thanks.
