### ISSUE TITLE
Comparison to -1

### ISSUE THREAD

**Issue by alexlur** [WebReflection/document-register-element#57]
I saw a lot of index comparisons like `(-1 < index)`. Is there any case `Array#indexOf` returns a value lower than -1 or `NaN`?

**Comment by alexlur** [comment]
Never mind I read the arrow wrong.

**Comment by RangerMauve** [comment]
Just for the record, `indexOf` always returns either the index the element was found at, or -1. Never less than -1, and never NaN.
