### ISSUE TITLE
Custom Child Elements for Custom Elements

### ISSUE THREAD

**Issue by obihill** [WebReflection/document-register-element#60]
Hi,

I'd like to better understand the right way to create custom elements with custom child elements using this tool.

For example, say I want to have the following code:

```
<x-foo>
    <x-foo-child>child content</x-foo-child>
</x-foo>
```

Do I just call `document.registerElement` for both custom elements?

Thanks.

**Comment by RangerMauve** [comment]
Yes

**Comment by obihill** [comment]
Thanks a lot
