### ISSUE TITLE
attributeChangedCallback isn't called for initial attribute of a created element

### ISSUE THREAD

**Issue by ju-lien** [WebReflection/document-register-element#65]
Hi,

When an instance of a custom element is created it seems the [specs](https://w3c.github.io/webcomponents/spec/custom/#html-creating-and-inserting-nodes) (4.3.8) say that attributeChangedCallback() have to be fired for all initial attributes.

e.g.
`<my-dom test="mytest">test</my-dom>`
```javascript
class MyDom extends HTMLElement {

  static get observedAttributes() {
    return ['test'];
  }
  attributeChangedCallback(name, oldValue, newValue) {
    console.log(name + ':' + newValue);
  }
}
customElements.define('my-dom', MyDom);
```

should fire attributeChangedCallback() when the element is parsed and created.

And as you can see in this [jsfiddle](https://jsfiddle.net/pvhe8gzf/1/) it's not the case.

I'm on chrome beta but it's the same in firefox.

And you can test the same code in chrome canary with custom element enabled [here](https://jsfiddle.net/0nnysatr/)

Thanks

**Comment by WebReflection** [comment]
actually only for initial attribute that are available, not just all of them. Thanks for filing this

**Comment by WebReflection** [comment]
fixed and tested in latest push.
