### ISSUE TITLE
Webpack out-of-box compatibility

### ISSUE THREAD

**Issue by treshugart** [WebReflection/document-register-element#66]
It seems Webpack tries to build in its AMD shim when bundling the `.max` version in your `bundle/` directory. I'm assuming that it finds what it thinks are references to `define` being used, but I haven't singled out exactly which lines of code are causing it to do that yet.

**Comment by treshugart** [comment]
Figured it out and raised a PR. Unfortunately, I don't know of a good way to write a test for this (but I did run your tests and they pass).

**Comment by WebReflection** [comment]
the and module is https://github.com/WebReflection/document-register-element/blob/master/build/document-register-element.max.amd.js

however, I use `define` as function name in the generic one which is wrapped in a closure so I'm not sure why that bothers webpack.
