### ISSUE TITLE
Elements in ShadowDOM not being instantiated?

### ISSUE THREAD

**Issue by trusktr** [WebReflection/document-register-element#68]
I'm not sure if it's a problem with your v0, or the Chrome v0 API, but I've noticed that when I put my custom elements inside a shadow tree, the `createdCallbacks` don't get called.

(I haven't migrated to v1 yet.)

For example, I've got code like the following (assume that the `motor-node` and `motor-scene` elements have created callbacks that log to console "created!":

```js
import React from 'react'
import ReactDOM from 'react-dom'
import sleep from 'awaitbox/timers/sleep'
import startup from 'awaitbox/meteor/startup'
import 'infamous/motor-html' // this imports document-register-element

await startup()

ReactDOM.render(
    <motor-scene id="scene">
        <motor-node id="distributedNode">
        </motor-node>
    </motor-scene>,
    document.querySelector('#app-root')
)

await sleep(500)

let scene = document.querySelector('#scene')

let root = scene.createShadowRoot()

root.innerHTML = `
    <motor-node id="innerNode">
        <content></content>
    </motor-node>
`

console.log(root)
```

As you see, there are three total `motor-` elements, one of which is inside a shadow tree. `createdCallback` is only called for the ones outside the tree, and never for the motor-node inside the shadow tree.

## Reproduction

```sh
git clone git@github.com:trusktr/site --branch document-register-element-issue-68 --single-branch
cd site/meteor-app
npm install
meteor
```

Requires Meteor installed from http://meteor.com.

**Comment by trusktr** [comment]
Aha, I noticed something peculiar! If I change the code

```js
    root.innerHTML = `
        <motor-node id="innerNode">
            <content></content>
        </motor-node>
    `
```

to an imperative version like

```js
    let innerNode = new MotorHTMLNode
    root.appendChild(innerNode)
    innerNode.appendChild(document.createElement('content'))
```

then it works, and the `createdCallback`, etc, methods are fired.

**Comment by WebReflection** [comment]
`innerHTML` is a special case: https://github.com/WebReflection/document-register-element#using-innerhtml

Basically you need to include this script after this polyfill:
https://github.com/WebReflection/document-register-element/blob/master/build/innerHTML.max.js

and when needed, use the following form instead:
```js
innerHTML(root, `
  <motor-node id="innerNode">
    <content></content>
  </motor-node>
`);
```

I know it's not super elegant (also right now this is not compatible with V1 `{is:'element'}` but I'll fix that, but I think `innerHTML` is usually meant to bring performance boost so I don't feel too comfortable overwriting it *but* maybe I will to avoid surprises.
