### ISSUE TITLE
"Cannot read property 'create' of undefined"

### ISSUE THREAD

**Issue by Riim** [WebReflection/document-register-element#69]
Привет!
Если элемент сперва использован в разметке, а затем (ниже) определён, происходит ошибка: https://yadi.sk/i/_vIUE9MjuWRNH . Если поменять местами -- ошибка исчезает.
v1.0.7, в 0.5.4 её не было.
Спасибо.

**Comment by WebReflection** [comment]
Have you defined the element before creating one?

**Comment by Riim** [comment]
Conversely:
1. [created](https://github.com/Riim/Rionite/blob/master/examples/SimpleCounter.html#L9)
2. [defined](https://github.com/Riim/Rionite/blob/master/examples/SimpleCounter.html#L15)

**Comment by WebReflection** [comment]
I don't know what your library does, but if it overloads the constructor after definition then we have a problem. If not, I need to find time to dig into your library code, unless you find a way to reproduce the problem using only JS because my tests show green light for similar scenarios.

http://webreflection.github.io/document-register-element/test/

**Comment by Riim** [comment]
Translated by google:
I made a working example of a separate branch: https://github.com/Riim/Rionite/tree/update-document-register-element

For run:
```
> git clone https://github.com/Riim/Rionite.git -b update-document-register-element
> cd Rionite
> npm i
open in browser examples/SimpleCounter.html or examples/TodoApp.html
```

Everything works, but this error in the console.

I'm also a little change your polyfill: https://github.com/Riim/Rionite/blob/update-document-register-element/polyfills/document-register-element.max.js#L921 .
Unfortunately my English not enough to [explain](https://github.com/WebReflection/document-register-element/pull/59) why I do, but without this change TodoApp breaks down and with debugging you will be able to understand how it happens and that change is definitely needed.

For rebuild:
```> npm run build```



Original:
Я сделал рабочий пример отдельной веткой: https://github.com/Riim/Rionite/tree/update-document-register-element

Для запуска:
```
> git clone https://github.com/Riim/Rionite.git -b update-document-register-element
> cd Rionite
> npm i
open in browser examples/SimpleCounter.html or examples/TodoApp.html
```

Всё работает, но в консоли эта ошибка.

Так же я немного изменяю ваш полифил: https://github.com/Riim/Rionite/blob/update-document-register-element/polyfills/document-register-element.max.js#L921 . К сожалению моего английского не хватило что бы [объяснить](https://github.com/WebReflection/document-register-element/pull/59) зачем я так делаю, но без этого изменения TodoApp ломается и подебажив вы сможете понять как это происходит и что изменение определённо нужное.
Для пересборки:
```> npm run build```

**Comment by Riim** [comment]
I forgot about ["self"](https://github.com/Riim/Rionite/pull/3/commits/3b1a5f97dc6fdc7f659bb31cc8e66c800f69489a#diff-81625b80aaade16fa19bceb2a6ca270fR42), with him there is no error.
Sorry to disturb you.

**Comment by Riim** [comment]
Ошибка происходит в 55.0.2859.0 canary (64-bit) .

**Comment by WebReflection** [comment]
which version?

**Comment by Riim** [comment]
1.0.9

**Comment by Riim** [comment]
In following browsers all is well:
Chrome 52.0.2743.116 (64-bit)
Safary 9.1.1 (11601.6.17)
Opera 39.0.2256.71
Firefox 48.0.1

For repeating:
```
> git clone https://github.com/Riim/opal-components
open in browser opal-components/examples.html
```

**Comment by WebReflection** [comment]
can you try 1.0.10 ?

**Comment by WebReflection** [comment]
test page here: http://webreflection.github.io/document-register-element/test/

**Comment by Riim** [comment]
Error has disappeared, thank you.
