### ISSUE TITLE
IE <= 10 doesn't fire attributeChangedCallback for initial values if it's an empty string (boolean attribute)

### ISSUE THREAD

**Issue by treshugart** [WebReflection/document-register-element#70]
See http://codepen.io/treshugart/pen/bZXgYB (tested in IE10, should be the same in IE9).

Basically, IE has a bug where the mutation event `prevValue` is an empty string on the initial set. If your new value is also an empty string the change handler doesn't fire because they're equal. The use-case here is when setting boolean attributes: `element.setAttribute('test', '')`.

I believe this exists in both IE 9 and 10, but unsure if it will occur in your IE8 fill. When we had this built into Skate awhile back, the fix was to keep track of the previous value manually and compare it to the one we had on record instead of relying on the one from the event.

**Comment by treshugart** [comment]
Found the fix in our deprecated polyfill: https://github.com/skatejs/polyfill-mutation-observer/blob/master/src/index.js#L223. There's actually a lot of IE fixes in there that might be worth looking at, if you're interested.

**Comment by treshugart** [comment]
Simple fix for now would be to include the `MutationObserver` polyfill from `webcomponents.js`.

**Comment by WebReflection** [comment]
Weird I haven't spot this before, there should be a test to cover this.

I'll have a look this evening and hopefully I won't need `MutationObserver` polyfill from `webcomponents.js`, specially because this is an alternative to that repo ;-)

**Comment by treshugart** [comment]
Nah, wasn't saying you should use it, it's just a possible workaround for those who might be affected by this.

**Comment by WebReflection** [comment]
luckily enough, the issue was that IE9 and IE10 weren't setting `newValue` and `prevValue` as null but as empty string. Although these are aware about the fact the attribute wasn't there or was removed so ... no MutationObserver needed at all ^_^

**Comment by treshugart** [comment]
Nice! Thanks @WebReflection.

**Comment by treshugart** [comment]
After integrating it into Skate, I've noticed the Opera 12 tests are failing https://travis-ci.org/skatejs/skatejs/builds/156798735. These are the same tests that failed for IE before the fix you made. Just going to bed now, so I haven't looked much further, but I think Opera might have worked with the `prevValue` and IE needs the fixes you made. IIRC that's possibly why we may have had to store the value manually, but I'm not certain.

**Comment by WebReflection** [comment]
there should be no side effects in the change I've made here:
https://github.com/WebReflection/document-register-element/commit/7c8de8fe9656d02367ae0658d0841749fbf659a1#diff-27e2f089a8f6e83fee5d63beb9ca4acdL1075

if Opera was working before, it should keep working now. The only possible glitch I see is that when before it was failing the first check, there's now a chance it doesn't fail the rest, or `attrChange` has no value? I will investigate this evening.

Btw, "_how do you Travis Opera 12_" ? If I can automate browsers testing in here too, that'd be awesome.

**Comment by WebReflection** [comment]
Opera 12 has been fixed
