### ISSUE TITLE
Meteor breaks document-register-element?

### ISSUE THREAD

**Issue by trusktr** [WebReflection/document-register-element#72]
I'm not sure if I should post here or at Meteor, but v1.0.7 breaks Meteor apps for some reason. When the only line of code I have in my Meteor app is:

```js
import 'document-register-element'
```

I get the following error in console:

![screen shot 2016-08-30 at 1 43 29 am](https://cloud.githubusercontent.com/assets/297678/18082321/30496658-6e53-11e6-9b9c-ca57737c3653.png)

**Comment by trusktr** [comment]
Reproduction (requires `meteor` command to be installed):

```sh
git clone git@github.com:trusktr/meteor --branch issue-7736 --single-branch
cd meteor
./run-dev.sh
```

**Comment by trusktr** [comment]
I also reported it at Meteor: https://github.com/meteor/meteor/issues/7736

**Comment by WebReflection** [comment]
if Meteor imports this repo after it pollutes some global it might be a problem. This repo should be included upfront any other DOM based library.

I might consider copying over public statics though ...

**Comment by WebReflection** [comment]
I'm very confused by this: https://github.com/meteor/meteor/issues/7738

**Comment by WebReflection** [comment]
I am going to close this ticket as invalid if nothing happens during the weekend.

Best regards

**Comment by trusktr** [comment]
Hi Andrea, the relevant issue is just https://github.com/meteor/meteor/issues/7736, sorry to cause the confusion with the wrong title.

**Comment by WebReflection** [comment]
You are using `webcomponents.js` there, right? why or how is this polyfll involved ?

**Comment by trusktr** [comment]
Yeah, https://github.com/meteor/meteor/issues/7736 has nothing to do with your polyfill, I meant to put WebComponents.js in the title, and you can safely unsubscribe from that one.

The issue here is valid though, and can be reproduced with the steps above.

**Comment by trusktr** [comment]
Opened a new issue at https://github.com/meteor/blaze/issues/95

**Comment by trusktr** [comment]
@WebReflection [This line](https://github.com/WebReflection/document-register-element/blob/master/src/document-register-element.js#L904) sets the `HTML` property on the window, which overrides Meteor's global `HTML` property. The `htmlClass.get(/^HTML/)` call returns an array that contains the value `"HTML"` representing the `<html>` element constructor.

Maybe you should ensure that the polyfill does not add constructors that don't exist onto `window`. f.e. the native `HTMLHtmlElement` constructor exists out-of-the-box, but `HTML` does not.

**Comment by trusktr** [comment]
I also noticed that `polyfillV1()` gets called twice (in Chrome). Is that needed?

**Comment by trusktr** [comment]
On [these lines](https://github.com/WebReflection/document-register-element/blob/master/src/document-register-element.js#L902-L903), the check passes because Meteor has added the `HTML` property to the `window` before the polyfill is imported.

**Comment by WebReflection** [comment]
> Ideally no new globals should be set, only existing ones overridden.

Agreed. We can also agree that Meteor is the obtrusive here adding a global HTML object instead of using it's own namespace.

I will avoid unnecessary pollution, I am not even sure why `HTML` is returned. Will double check.

For anything else please open a ticket a part. Thank you.

**Comment by WebReflection** [comment]
P.S. there is a reason `polyfillV1` can be called twice. One is to make it available where not available yet, another is to test that it works as expected in case it was already available.

Some browser was crashing within the `try` if not available at all.
Performance impact: 0

So it'll stay like that.

**Comment by WebReflection** [comment]
can you please test latest and tell me if this problem is gone? I've also improved the try/catch and other few things to avoid duplicated poly

**Comment by trusktr** [comment]
@WebReflection Cool, it works! :}
