### ISSUE TITLE
Versions missing on NPM.

### ISSUE THREAD

**Issue by trusktr** [WebReflection/document-register-element#73]
Versions between 0.5.4 and 1.0.0 are not published on NPM, so for now I'm getting 0.6.1 from GitHub and using v0 API for the meantime due to #72.

package.json:

```json
  "dependencies": {
    "document-register-element": "WebReflection/document-register-element#0.6.1",
  }
```

**Comment by treshugart** [comment]
Why can't you use latest?

**Comment by trusktr** [comment]
In Meteor, because of https://github.com/meteor/meteor/issues/7736 and https://github.com/WebReflection/document-register-element/issues/72.

**Comment by WebReflection** [comment]
I have added version 0.6.1 to npm
