### ISSUE TITLE
attributeChangedCallback not being called

### ISSUE THREAD

**Issue by trusktr** [WebReflection/document-register-element#76]
Now that I have things running, I noticed that `attributeChangedCallback` isn't being called. I have code like the following:

```js
import 'document-register-element'

class MyEl extends HTMLElement {
    constructor() {
        super()
        console.log('my-el constructed')
    }

    connectedCallback() {
        console.log('my-el connected')
    }

    disconnectedCallback() {
        console.log('my-el disconnected')
    }

    attributeChangedCallback(attr, oldVal, newVal) {
        console.log('my-el attribute changed', attr)
    }
}

customElements.define('my-el', MyEl)

let myEl = document.createElement('my-el')

document.body.appendChild(myEl)

myEl.setAttribute('foo', 'bar')

myEl.remove()
```

Expected output:

```
my-el constructed
my-el connected
my-el attribute changed foo
my-el disconnected
```

Actual output:

```
my-el constructed
my-el connected
my-el disconnected
```

**Comment by treshugart** [comment]
Have you tried queueing a macrotask (setTimeout()) to remove the element so the Mutation Observer (microtask) has time to fire?

**Comment by trusktr** [comment]
@treshugart I haven't, but if I don't remove the element, f.e.

```js
import 'document-register-element'

class MyEl extends HTMLElement {
    constructor() {
        super()
        console.log('my-el constructed')
    }

    connectedCallback() {
        console.log('my-el connected')
    }

    disconnectedCallback() {
        console.log('my-el disconnected')
    }

    attributeChangedCallback(attr, oldVal, newVal) {
        console.log('my-el attribute changed', attr)
    }
}

customElements.define('my-el', MyEl)

let myEl = document.createElement('my-el')

document.body.appendChild(myEl)

myEl.setAttribute('foo', 'bar')

//myEl.remove()
```

then the output is just

```
my-el constructed
my-el connected
```

**Comment by treshugart** [comment]
Ah, I should have noticed this before. In v1 you need to define `observedAttributes`.

```js

class MyEl extends HTMLElement {
  ...
  static observedAttributes = ['foo']
  // or
  static get observedAttributes() {
    return ['foo'];
  }
  ...
}
```

**Comment by WebReflection** [comment]
when in doubt, check the test file. You need to specify a list of attribtues through a static `observedAttributes` as tested in here:
https://github.com/WebReflection/document-register-element/blob/master/test/document-register-element.js#L117-L143

**Comment by WebReflection** [comment]
Moreover, check the `super()` caveat: https://github.com/WebReflection/document-register-element#v1-caveat

**Comment by trusktr** [comment]
@WebReflection @treshugart There is only a [single algorithm](https://w3c.github.io/webcomponents/spec/custom/#element-definition) that uses `observedAttributes` in the spec, and that algorithm doesn't specify what happens when it is undefined, it only specifies what happens when it is "not undefined".

[Section 2.6](https://w3c.github.io/webcomponents/spec/custom/#custom-element-reactions) also says

> When any of [a custom element's] attributes are changed, appended, removed, or replaced, [the custom element's] attributeChangedCallback is run.

Did I miss something spec? Or are you guys just following what Chrome is implementing natively?

Personally, I'd like for  `observedAttributes` to be optional, then if it is undefined  `attributeChangedCallback` would fire for all attributes like in v0. Having this functionality would be opt-in.

**Comment by WebReflection** [comment]
Interesting. "Guys" (just me here, no plural) took Chrome as reference
indeed. For perfomance sake, I thought it was mandatory to specify a list
of attributes and I don't see any advantage in having a filter opt-in.
However, if that's what specs are saying, I might just drop the filter if
the list is missing or ...empty? What if the list is defined but empty?
Blacklisting everything?

**Comment by trusktr** [comment]
If defined but empty, maybe attributeChangedCallback never gets called, if that's what you meant by "Blacklisting everything"?

**Comment by WebReflection** [comment]
I've followed the discussion and it turns out this poly is doing the right
thing already

**Comment by trusktr** [comment]
It's almost moot, because to be backwards compatible with v0 (which doesn't
have observedAttributes) we still have to write the conditional checks for
all attributes.

**Comment by WebReflection** [comment]
if specs change please let me know, thanks.
