### ISSUE TITLE
Spec isn't clear what happens with custom element adoption into new document.

### ISSUE THREAD

**Issue by trusktr** [WebReflection/document-register-element#77]
Are custom elements supposed to be defined in the destination document or it won't work? Does adopting a custom element from an iframe (for example) automatically register associated custom elements in the destination document? The spec isn't clear on that.

What is clear is that `adoptedCallback` will be called, which implies that the instance remains alive when transferred across documents, but that's about it.

**Comment by WebReflection** [comment]
This poly is not cross frame aware and until specs will be clear on that
I'm not planning to waste too much time on it. V1.1.0 is the first that
exports a function to install CE on an iframe, let's see what/how users
will take advantage of it.

**Comment by trusktr** [comment]
Oops, thanks for the reply, but I meant to post this at the w3c repo! Yeah, that seems difficult to polyfill anyways.
