### ISSUE TITLE
Uncaught DOMException: custom element constructors must call super() first and must not return a different object

### ISSUE THREAD

**Issue by Riim** [WebReflection/document-register-element#79]
v1.1.1
Error after update Chrome to version `55.0.2867.0 canary (64-bit)`: `Uncaught DOMException: custom element constructors must call super() first and must not return a different object`.

Occurs when the element is in the DOM before its definition.
When debugging line `Reflect.construct(Class, empty, info.constructor)` is called and the error occurs immediately after exiting the function `CustomElementsV1`.

**Comment by WebReflection** [comment]
https://github.com/WebReflection/document-register-element#v1-caveat

**Comment by Riim** [comment]
Thanks! It is my [error](https://github.com/Riim/Rionite/commit/482263a1e390ab220861c368e570917620364f11#diff-81625b80aaade16fa19bceb2a6ca270fL54).
