### ISSUE TITLE
Comparison to webcompents/custom-elements

### ISSUE THREAD

**Issue by seaneking** [WebReflection/document-register-element#81]
Now that Polymer's v1 custom elements polyfill has been split out into [webcomponents/custom-elements](https://github.com/webcomponents/custom-elements), it would be helpful to have a direct comparison between that and `document-register-element` for onlookers.

Custom-elements doesn't support extending built-ins yet (though apparently coming soon), other than that's is <IE10 support in document-register-element the main difference?

**Comment by WebReflection** [comment]
I haven't read the entirety of the other polyfill but these are few difference that comes to my mind:

  * DRE supports both V1 and a battle tested V0 down to Android 2, IE8, BB OS, and other old browsers.
  * DRE doesn't need additional polyfills.
  * DRE supports extending builtins already, as well as real classes, not only transpiled one (not sure the other poly is there too)
  * DRE is more deployed than others: Mozilla, Google AMP, Cordova, many other projects has been using DRE for 2 years or more now.
  * DRE is bigger but still relatively small: it's around 5KB
  * Used as CommonJS module, DRE can be installed in any iframe or window without needing to re-include the source: https://github.com/WebReflection/document-register-element/blob/master/build/document-register-element.node.js#L1423-L1425

The other poly looks clean and simple, thanks to its native ES target (DRE targets ES5+ browsers without needing to be transpiled) and thanks to its support confined to modern browsers only.

If you don't need to extend native builtins and you don't care about last 5 years browsers panorama but only latest engines, you might want to consider the other poly instead.

Please also note that Polymer project uses [a different version of the same polyfill](https://github.com/webcomponents/webcomponentsjs/tree/v1-polymer-edits) so it's not clear how they're going to maintain two polyfills that shim the same thing at once (in terms of inter-compatibility)

It'd be cool to have some info from their team too and now that I think about it:
DRE has only me as maintainer, the other one has more people so it might get updates faster.

Thankfully once specs are met, there's not much to update if not obvious bugs.
I'm quite fast to update and solve problems, but I'm 1 against many :-)

**Comment by seaneking** [comment]
Awesome. This should be in the README, IMO. 

Also just to clarify - is v1 supported down to IE8, or just the v0? Also, any plans to split out the v0 support into a different build target (breaking change obvs) to save some weight for those just using v1 spec?

**Comment by WebReflection** [comment]
> is v1 supported down to IE8, or just the v0?

v1 works down to IE8 too

> any plans to split out the v0 support into a different build target?

not in the short term because v1 is currently based on top ov v0, which is why it's  compatible and more battle tested than anything else

> to save some weight for those just using v1 spec?

with all the thing developers include these days, 5KB gzipped polyfill are the last problem the Web stack has: it's nothing.

In all reasons that would make me think of maintaining and splitting this poly in two, its size is the least relevant of all.

**Comment by thomaswilburn** [comment]
It's worth noting that if you use the Polymer shim, it can work in IE10, but only if you include the Mutation Observers shim, plus shims for Map and Set. Once those are included in the bundle size, it and DRE are probably pretty comparable in terms of weight.

**Comment by simevidas** [comment]
It looks like  custom-elements/src/custom-elements.js supersedes webcomponentsjs/src/CustomElements/v1/CustomElements.js: [diff](https://www.diffchecker.com/9Qfb2udY). I’d expect Polymer to switch to the new version, if they already haven’t.
