### ISSUE TITLE
Error in Safari (using v1)

### ISSUE THREAD

**Issue by epoberezkin** [WebReflection/document-register-element#82]
Class is extended from HTMLElement:

```javascript
class MyElement extends HTMLElement {
  constructor(self) {
    return super(self);
  }

  // ...
}

customElements.define('my-element', MyElement);
```

I am getting this error:
```
TypeError: HTMLElementConstructor is not a constructor (evaluating 'super(self)')
```

Without constructor I am getting a similar error
```
TypeError: HTMLElementConstructor is not a constructor (evaluating 'super(...arguments)')
```

Works in chrome in both cases.

**Comment by SerkanSipahi** [comment]
@epoberezkin see here similar safari problem with solution: https://github.com/google/traceur-compiler/issues/1709

**Comment by WebReflection** [comment]
Are you transpiling? If that's the case, it's an open bug in Babel and a
known problem with all builtins extends in Babel

**Comment by WebReflection** [comment]
Just tried in the test page:
http://webreflection.github.io/document-register-element/test/

```js
> class MyElement extends HTMLElement {
  constructor(self) {
    return super(self);
  }

  // ...
}

customElements.define('my-element', MyElement);

let myEl = new MyElement();

document.body.appendChild(myEl);
// <my-element></my-element>
```
Not a glitch on Safari

**Comment by WebReflection** [comment]
@SerkanSipahi ... don't do that, no need. This polyfill works just fine.

**Comment by treshugart** [comment]
We had a similar problem running ranspiled ES5 with native v1. You have to do something like https://github.com/skatejs/skatejs/blob/master/src/api/component.js#L123.

**Comment by SerkanSipahi** [comment]
@WebReflection on which Safari Version do you test it?

**Comment by WebReflection** [comment]
@SerkanSipahi Version 10.0 (11602.1.50.0.10)

**Comment by SerkanSipahi** [comment]
I have tested in Version 9.1.3 and it works, too. Will change from v0 to v1 :)
