### ISSUE TITLE
attachShadow override calls back to locally cached version

### ISSUE THREAD

**Issue by treshugart** [WebReflection/document-register-element#84]
Currently the `attachShadow()` override to observe shadow roots calls back to locally scoped  copy of the previous `attachShadow()` found at time it is loaded. If you include DRE prior to the override, then DRE never calls back the override. This means that you must include any overrides prior to including DRE. Unfortunately, the ES2015 module spec doesn't guarantee order and neither does AMD, leaving CJS / `<script />` tags as the only reliable alternative to ensure order.

**Comment by treshugart** [comment]
In retrospect, this is kinda silly. I'll find a way to ensure my fix gets applied prior to loading DRE.

**Comment by WebReflection** [comment]
we had another issue that was complaining about the popposite case ... DRE calling patched stuff instead of using original one.

So yeah, being sure about your dependencies order *is* your responsibility and DRE uses, and trap, whatever it finds (if it does)
