### ISSUE TITLE
Some V1 examples in README.md and in other sites not working !

### ISSUE THREAD

**Issue by SerkanSipahi** [WebReflection/document-register-element#85]
In Chrome Canary v56.0.2891.0 where is V1 ( natively ) available are the most examples with "extend native components" not working ! 

Example on  README.md not working
```js
// extends some different native constructor
class MyButton extends HTMLButtonElement {}

// define it specifying what's extending
customElements.define('my-button', MyButton, {extends: 'button'});

// append this in dom "<button is="my-button">click me</button>" not working

// creating with new not working
document.body.appendChild(
  new MyButton
).textContent = 'click me';
```

Error:
```error
VM302:1 Uncaught TypeError: Illegal constructor
    at MyDom (<anonymous>:1:1)
    at <anonymous>:11:10
```

Same effect with examples (extend native components) on this sites not working
- https://developers.google.com/web/fundamentals/getting-started/primers/customelements
- https://www.w3.org/TR/custom-elements/

This was a minimal analysis !

My Question, whats going wrong and is v1 really ready for production?
Do you think the Polyfill mirror the spec (W3C Working Draft)? and i think the spec not behave as expected!

**Comment by WebReflection** [comment]
> My Question, whats going wrong

are you transpiling? if the answer is yes, you are pointing the finger at the wrong issue (neither Canary, nor this polyfill)

> is v1 really ready for production?

it's not even finished, not sure how to answer this. Few parts are ready for production and available through this poly.

Developer browsers might be unstable, and I won't fix them, but I'll ensure stable browsers will work.

Firefox nightly, for instance, is a black hole of errors so far. It exposes the API and it throws with 3/4 of it: I don't care.

> Do you think the Polyfill mirror the spec (W3C Working Draft)?

It does its best to polyfill them. Few parts of the specs are unpolyfillable.

The constructor is one of these cases, described in here: https://www.webreflection.co.uk/blog/2016/08/30/js-super-problem and also in this repo: 
https://github.com/WebReflection/document-register-element#v1-caveat

**Comment by SerkanSipahi** [comment]
> are you transpiling? if the answer is yes, you are pointing the finger at the wrong issue (neither Canary, nor this polyfill)

as well ... as ! Without compiling in Canary ( v56.0.2891.0) the "extend native components" e.g. button, form, ui, etc not working, you are right , maybe because its not a stable browser!

The problem is i have/must to transpile my code. With v0 i have no problems when extending native components (HTMLButtonElement, HTMLImageElement, etc). Im using an other polyfill for v0. 
I had hoped i can change to v1 with your polyfill but its not possible for me at the moment.

I thinkg v1 is in 1 - 2 years ready for production (incl. polyfill) like v0 !

Thank you for your answer :)

**Comment by WebReflection** [comment]
It works on chrome and so does v0 too. Use the test page and go in console
to try 'cause Canary last time I've checked was OK

**Comment by WebReflection** [comment]
P.S. you can't transpile V1, there is a Babel bug for this issue

**Comment by SerkanSipahi** [comment]
> It works on chrome and so does v0 too. Use the test page and go in console
to try 'cause Canary last time I've checked was OK

What i mean is, i paste (without compiling) following code in stable Chrome v54.0.2840.59 where is "customElements.define" is available (natively). It does not work. Getting error:

```js
// extends some different native constructor
class MyButton extends HTMLButtonElement {}

// define it specifying what's extending
customElements.define('my-button', MyButton, {extends: 'button'});

// append this in dom "<button is="my-button">click me</button>" not working

// creating with new not working
document.body.appendChild(
  new MyButton
).textContent = 'click me';
``` 
error:
```log
VM302:1 Uncaught TypeError: Illegal constructor
    at MyDom (<anonymous>:1:1)
    at <anonymous>:11:10
```

> P.S. you can't transpile V1, there is a Babel bug for this issue

Maybe its time to develop a new bubel-plugin (https://www.webreflection.co.uk/blog/2016/08/30/js-super-problem#not-so-easy-though). I think i can do that (https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md). Will give you feedback in some days.

**Comment by WebReflection** [comment]
I've tried right now on this page
http://webreflection.github.io/document-register-element/test/

opening the console.

Everything works fine.

<img width="514" alt="ce-demo" src="https://cloud.githubusercontent.com/assets/85749/19441934/71833890-947f-11e6-9699-4284ace61a03.png">

**Comment by WebReflection** [comment]
Canary Version 56.0.2891.0 canary (64-bit)

**Comment by SerkanSipahi** [comment]
@WebReflection Please open "NOT" your Testpage ! "OPEN" www.google.com (no polyfill) with v56.0.2891.0 canary or with v54.0.2840.59 and then paste the code. The code does not even work in a stable version( v54.0.2840.59). Why i should use an polyfill that not working on stable version where is v1 available. I hope you understand this time what i mean !!!!

**Comment by WebReflection** [comment]
I see ... you were complaining about non polyfilled case but then I'm not sure why you would open a bug in here ... btw, now I understand your last question:

> Do you think the Polyfill mirror the spec (W3C Working Draft)? and i think the spec not behave as expected!

**Yes**, this polyfill implements W3C specs [including native builtins extend](https://www.w3.org/TR/custom-elements/#custom-elements-customized-builtin-example)

**Comment by SerkanSipahi** [comment]
> I see ... you were complaining about non polyfilled case but then I'm not sure why you would open a bug in here ... btw, now I understand your last question:

because v54.0.2840.59 is stable and v1 is available and then i assume that should works !

**Comment by WebReflection** [comment]
Wrong assumption. Firefox Nightly exposes a completely broken API and Safari wasn't implementing `.when` and `.get`

This is a polyfill that brings Custom Elements V1 on every browser that was previously compatible/polyfilled for V0

**Comment by SerkanSipahi** [comment]
you had written:
> Developer browsers might be unstable, and I won't fix them,  >>>> but I'll ensure stable browsers will work. <<<<

**Comment by WebReflection** [comment]
Indeed Firefox stable, as well as Chrome, and Safari, are working.

How can I help you now? ...

**Comment by SerkanSipahi** [comment]
> Indeed Firefox stable, as well as Chrome, and Safari, are working.

Yes you could help me. With polyfill it works and without it not work. The browsers are not yet ready.

**Comment by SerkanSipahi** [comment]
> edit: all supported browsers here https://github.com/WebReflection/document-register-element#tested-on

i know now, your polyfill works according the spec

**Comment by SerkanSipahi** [comment]
@WebReflection What do you think about a babel-plugin for compiling a better code (https://www.webreflection.co.uk/blog/2016/08/30/js-super-problem)?

**Comment by WebReflection** [comment]
> The browsers are not yet ready although in stable available.

do you understand this polyfill exists so you don't care about when browsers would be ready?
That's the entire purpose of having polyfills. After a while you drop them because natively implemented ... right?

> What do you think about a babel-plugin for compiling a better code?

there is a bug already on babel repo.
https://github.com/babel/babel/issues/4480

Feel free to push a PR or help resolving, thanks.

**Comment by SerkanSipahi** [comment]
> do you understand this polyfill exists so you don't care about when browsers would be ready?
That's the entire purpose of having polyfills. After a while you drop them because natively implemented ... right?

right

> Feel free to push a PR or help resolving, thanks.

i will try to solve this problem.
