### ISSUE TITLE
V1 constructor this

### ISSUE THREAD

**Issue by thepian** [WebReflection/document-register-element#87]
I understand the general concern about the constructor call in V1. However should it not be possible to extract the constructor as a function? I know that there are restrictions to calling classes without new in ES6, but there might be ways around it, at least for transpiled source.

If you instantiatiate the class and get the constructor for the instance, is that a callable function?

**Comment by WebReflection** [comment]
No

**Comment by WebReflection** [comment]
Update: the patch proposed by the WebKit developer is as broken as any other patch so Babel users are stuck behind this problem.
