### ISSUE TITLE
Safari not working with Custom elements V1

### ISSUE THREAD

**Issue by Shijir** [WebReflection/document-register-element#88]
Safari is throwing the following error for custom elements V1. Has anyone encountered this error?

[Error] Error: __
	
	
	
	
	eval code
	eval@[native code]
	invoke@http://localhost:3000/node_modules/zone.js/dist/zone.js:203:33
	run@http://localhost:3000/node_modules/zone.js/dist/zone.js:96:49
	http://localhost:3000/node_modules/zone.js/dist/zone.js:462:60
	invokeTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:236:42
	runTask@http://localhost:3000/node_modules/zone.js/dist/zone.js:136:57
	drainMicroTaskQueue@http://localhost:3000/node_modules/zone.js/dist/zone.js:368:42
	g@http://localhost:3000/node_modules/core-js/client/shim.min.js:8:10017
	http://localhost:3000/node_modules/core-js/client/shim.min.js:8:10139
	k@http://localhost:3000/node_modules/core-js/client/shim.min.js:8:14294
	Evaluating http://localhost:3000/icons/define-clarity-icons.js
	Error loading http://localhost:3000/icons/define-clarity-icons.js

	error
	invoke (zone.js:203)
	run (zone.js:96)
	(anonymous function) (zone.js:462)
	invokeTask (zone.js:236)
	runTask (zone.js:136)
	drainMicroTaskQueue (zone.js:368)
	g (shim.min.js:8:10018)
	(anonymous function) (shim.min.js:8:10140)
	k (shim.min.js:8:14295)

**Comment by matthewp** [comment]
Not sure if its the same issue, but Safari's HTMLElement.prototype.constructor is readonly. Since this polyfill's fake HTMLElement's prototype is the real HTMLElement.prototype, you can't do ES5 inheritance on it. webcomponents/custom-elements works, their fake HTMLElement.prototype is Object.created off the real one.

**Comment by WebReflection** [comment]
can anyone give me an example to look at?

There's not a single mention to this polyfill in the entire stack of errors!

**Comment by WebReflection** [comment]
P.S. I need a basic example to reproduce the issue **without** 3rd parts frameworks involved and/or transpiled. You can use the [test page](https://webreflection.github.io/document-register-element/test/) to simplify this task.

**Comment by matthewp** [comment]
```html
<!doctype html>
<script src="path/to/document-register-element.max.js"></script>
<script>
(function(){
  "use strict";

  function BaseElement(){

  }

  BaseElement.prototype = Object.create(HTMLElement.prototype);
  BaseElement.prototype.constructor = BaseElement;
})();
</script>
```

**Comment by WebReflection** [comment]
did you actually try that code? 'cause it doesn't throw a thing here.

Safari Version 10.0 (11602.1.50.0.10)

Moreover, `Object.getOwnPropertyDescriptor(HTMLElement.prototype, 'constructor').writable` is true even on a blank page.

This bug in any case has nothing to do with this polyfill.

**Comment by Shijir** [comment]
My Safari version is Version 9.1.1 (11601.6.17).

@matthewp's code throws a following error:
"TypeError: Attempted to assign to readonly property."

I also tried Object.getOwnPropertyDescriptor(HTMLElement.prototype, 'constructor').writable, which says "false".

**Comment by WebReflection** [comment]
what does `Object.getOwnPropertyDescriptor(HTMLElement.prototype, 'constructor').configurable` says? If that's a `true`:

```
function BaseElement(){}
BaseElement.prototype = Object.create(HTMLElement.prototype, {
  constructor: {
    configurable: true,
    value: BaseElement
  }
});
```

Since, [as you can see](https://github.com/WebReflection/document-register-element/blob/master/build/document-register-element.max.js#L1363-L1368), this polyfill doesn't suffer this issue and it uses a patched work around for old Safari, the bug is *still* invalid and not related to this polyfill.

Best Regards

**Comment by Shijir** [comment]
Thank you for your help. What else do you think the cause might be? We have isolated the case down to the base code @matthewp wrote with no other libraries. The only difference as far as I can see is the version of the safari browsers we are using.

**Comment by WebReflection** [comment]
If the test page is green, and IIRC it is, it uses the following code to extends constructors:

```js
function setProto(A, B) {
  A.prototype = Object.create(
    B.prototype,
    {constructor: {
      configurable: true,
      writable: true,
      value: A
    }}
  );
}
```

... so that you can ...

```js
function MyCE(self) {
  return HTMLElement.call(this, self);
}
setProto(MyCE, HTMLElement);
```

**Comment by WebReflection** [comment]
Are tests green?

**Comment by Shijir** [comment]
I am still seeing the error. "TypeError: Attempted to assign to readonly property" on Safari. But I am using typescript and it compiles to ES5. The compiled version has an error pointed at 3rd line of the following code.

var __extends = (this || self, this && this.__extends || function(d, b) {
            function __() {
                this.constructor = d
            }
            for (var p in b)
                b.hasOwnProperty(p) && (d[p] = b[p]);
            d.prototype = null === b ? Object.create(b) : (__.prototype = b.prototype, new __)
        })

**Comment by WebReflection** [comment]
yeah sorry, I don't fix TypeScript transpiled code in here.

**Comment by tconroy** [comment]
I'm encountering the exact same issue with TypeScript-transpiled code, @Shijir. Did you ever manage to find a fix for this?

**Comment by tconroy** [comment]
@WebReflection Thanks for the link! please correct me if I'm wrong but it seems that would have to be used in the source module ( which I don't have direct access to change ).

TBF I'm running into major abstraction issues (TypeScript -> ES2015 -> imported into my app via webpack -> loading CustomElement Polyfills ) and not sure how to just get the darn thing to work in Safari.

Have you managed to get CustomElements working in older mobile safari with a webpack build pipeline? Have any references you'd mind sharing?

**Comment by WebReflection** [comment]
I don't use transpilers, which is your problem.

Babel has the [same issue](https://github.com/babel/babel/issues/4480), and so does TypeScript: these are all broken, and since ever, which is why I've written the following post and **3** libraries to fix the problem in a different way.

https://medium.com/@WebReflection/a-case-for-js-classes-without-classes-9e60b3b5992

It surprises me many developers blindly chose transpilers without investigating all possible side-effects.

Today the Web is hurt more than ever due transpilers incapable of doing the right thing.

**Comment by tconroy** [comment]
I hear you. Unfortunately sometimes you're stuck on a project where you didn't get to make that fundamental architectural decision.  ¯/\_(ツ)_/¯

What is interesting is it is working as expected in modern browsers (chrome, iOS 10 Safari), but not iOS 9 or 8. It throws up on `this.constructor = d` can't assign to read-only property. No idea why and it is quite frustrating.

Anyway.. Thank you for your time, if you or anyone else have any ideas on how to fix this I am all ears. Cheers.

**Comment by WebReflection** [comment]
that's because typescript didn't bother assigning the constructor at class definition time.

The following line
```js
d.prototype = null === b ? Object.create(b) : (__.prototype = b.prototype, new __)
```

should've been
```js
Object.defineProperty(
  d.prototype = null === b ? Object.create(b) : (__.prototype = b.prototype, new __),
  'constructor',
  {value: d}
);
```

But hey, who am I to argue against Microsoft developers `¯\_(ツ)_/¯`

**Comment by WebReflection** [comment]
P.S. that is a known old WebKit gotcha with native properties, btw ... unfixable unless you monkey patch TypeScript for that case.

`obj.constructor` is usually never used/accessed anyway, consider doing that (monkey patching TypeScript)

**Comment by WebReflection** [comment]
P.S.2 with `CustomTag` you would extend the returned class ... you can skip `CustomTag` magic and use `Classtrophobic` directly though, it's just to bypass this WebKit issue.

The [ES5 Version](https://github.com/WebReflection/classtrophobic-es5#classtrophobic-es5--) is compatible with old WebKit too, you can test it directly on the link.
https://webreflection.github.io/classtrophobic-es5/test.html

**Comment by WebReflection** [comment]
P.S.Last

the usage of Classtrophobic is straight forward and you can use it as intermediate layer.

```js
// import Classtrophobic-ES5 as you want ... then ...
const TSHTMLElement = Class({
  extends: HTMLElement
});

// export TSHTMLElement, it's a class

// from now on ...
class MyElement extends TSHTMLElement {
  // yadayada
}
```
I hope this will work for you.

**Comment by tconroy** [comment]
Thank you so much for the comments @WebReflection. I'll definitely consider it if we can use it as an intermediary layer.. Dealing with this TS nonsense is driving me up the wall.

Cheers & thanks for your work on all these libs 👍

**Comment by dmitryshimkin** [comment]
While I fully agree that the issue should to be fixed in the TypeScript compiler (Even the new version 3 is still buggy!), I'd like to share an easy fix for this particular issue for anyone who might be interested:

```
// Insert this before any other transpiled code
Object.defineProperty(HTMLElement.prototype, 'constructor', { writable: true });
```
