### ISSUE TITLE
Uncaught DOMException: Failed to execute 'createElement' on 'Document': The result must not have attributes(…)

### ISSUE THREAD

**Issue by copleykj** [WebReflection/document-register-element#89]
Currently seeing this in a a project that uses OnsenUI, which depends on Custom Elements. Error didn't occur until the latest update to chrome but is now persistent. The issue seems to come from this line [here](https://github.com/WebReflection/document-register-element/blob/6f61557a6c9dc7839bada9999c8cfcbb26715553/build/document-register-element.node.js#L1007).

Current Environment Setup that might be relevant.

Onsen 2
React 15
Linux Mint 17, Chrome 54.0.2840.71 (64-bit)

**Comment by WebReflection** [comment]
that line tells me nothing, or better, it suggests me the problem is *not* from this polyfill.

I need a basic example to reproduce the issue without 3rd parts frameworks involved and/or transpiled.

**Comment by WebReflection** [comment]
P.S. You can use the [test page](https://webreflection.github.io/document-register-element/test/) to simplify this task.

**Comment by treshugart** [comment]
Chrome 54 has native custom elements and isn't DRE's issue. The spec says explicitly that this error will be thrown if you try and set attributes in the constructor. You can set properties, but attributes mist be deferred until `connectedCallback`.

**Comment by WebReflection** [comment]
Thank You
