### ISSUE TITLE
Any way to add property to elements before during constructor?

### ISSUE THREAD

**Issue by Maxlufs** [WebReflection/document-register-element#90]
I notice that all the property set on `this` during constructor was ignored, properties seem to only be abled to set during connectedCallback. 
```js
class TestElement extends HTMLElement {

	constructor() {
		super();
		console.log(`constructor`);
		this.asdf = 5
	}

	connectedCallback() {
		console.log(`connectedCallback`);
		console.log(this.asdf) // undefined instead of 5
	}
}
customElements.define('test-element', TestElement);
```
```html
document.body.appendChild(document.createElement('test-element'));
```

This is not how chrome 54 natively does it. Is there anyway to get away with this?

Thanks!

**Comment by WebReflection** [comment]
https://github.com/WebReflection/document-register-element#v1-caveat

**Comment by WebReflection** [comment]
I don't mean to be rude but too many keeps ignoring reading the README and/or using everything but this polyfill and come here with problems that are not related.

In your case, if it's an attribute, you are against specs: https://github.com/WebReflection/document-register-element/issues/89#issuecomment-255617061

If it's not, you didn't read the README.

```js
class TestElement extends HTMLElement {

    constructor(self) {
        self = super(self);
        self.asdf = 5;
        return self;
    }

    connectedCallback() {
        console.log(`connectedCallback`);
        console.log(this.asdf) // undefined instead of 5
    }
}
customElements.define('test-element', TestElement);
```

This is backward and forward compatible.

If you have issues that are not known, written in the README, and most of all polyfill related, feel free to open a new one.

Thank you.

**Comment by Maxlufs** [comment]
I see. The problem for me was actually in the 2nd example in the README ("Skipping the caveat through extends"), i didn't quite get how to pass the arguments of subclass's constructor to the base class (in my code there's some parameters passed from subclass to the base class to do some initial logic). After i tested it seems the constructor of subclass can be left out and leave the logic to `init()`, or have a constructor with a dummy `constructor(_){super(_)}`, although at least the argument has to be passed over otherwise it wouldn't work.

I think that should fix my issue. Thanks!

Is there a more technical explanation why there's this caveat and how the solution in README solves it? Any insights would be appreciated.

**Comment by Maxlufs** [comment]
For anyone who ran into the issue the property you added in `construtor`/`init` gets LOST in `connectedCallback` or any similar issue (especially in production where you need to take care of both chrome 54(native) and chrome 53(polyfill)), here's a clue you might be looking for.

As chrome 54 native custom elements don't support transpiled es5 code from babel, (hopefully they're gonna change that), there's a native shim you might have found here (https://github.com/webcomponents/custom-elements/blob/master/src/native-shim.js) that polyfills HTMLElement. **However, this shim conflicts with DRE when the element is constructed using `document.createElement`** (using new MyElement() turns out to be fine for me):

with native-shim.js: 

```js
(() => {
    let origHTMLElement = HTMLElement;
    window.HTMLElement = function() {
        // prefer new.target for elements that call super() constructors or
        // Reflect.construct directly
        let newTarget = new.target || this.constructor;
        return Reflect.construct(origHTMLElement, [], newTarget);
    }
    HTMLElement.prototype = Object.create(origHTMLElement.prototype, {
        constructor: {value: HTMLElement, configurable: true, writable: true},
    });
})();

class HTMLCustomElement extends HTMLElement {
    constructor(_) { return (_ = super(_)).init(), _; }
    init() { /* override as you like */ }
}

// create any other class inheriting HTMLCustomElement
class MyElement extends HTMLCustomElement {
    init() {
        // just use `this` as regular
        this.addEventListener('click', console.log);
        // no need to return it
        this.asdf = 5;
    }
    connectedCallback() {
        console.log(this.asdf)
    }
}
        customElements.define('my-element', MyElement);

 var element = document.createElement('my-element');
 document.body.appendChild(element); // console.log -> undefined
 var element = new MyElement();
 document.body.appendChild(element); // console.log -> 5
```
The result is found under Chromium Version 53.0.2785.143 Built on Ubuntu , running on Ubuntu 14.04 (64-bit).
It would work correctly without the shim. 

This means a guard is needed to make sure that it only polyfills chrome 54 but not anything else.
