### ISSUE TITLE
Object function HTMLElement() { [native code] } has no method 'call'

### ISSUE THREAD

**Issue by cramforce** [WebReflection/document-register-element#91]
We are seeing the error `Object function HTMLElement() { [native code] } has no method 'call'` in production.

Sample user agent `Mozilla/5.0 (Linux; U; Android 4.2.2; it-it; GT-I9060 Build/JDQ39) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30`

We tried reproing this with the Android 4.2.2 system browser but to no success. It may be flaky. I believe the consequence of this is that the custom element constructor (or `createdCallback`) is never called. We do, however, then see `connectedCallback` being called.

I was hoping that this may ring a bell, even without a repro case.

**Comment by WebReflection** [comment]
to start with, `HTMLElement` is overwritten in V1 so you shouldn't see `[native code]` in there.

I have an android 4 phone but I'm not sure it's 4.2, it's probably a 4.0 and it was tested and it was green.

It's also a quite pricey phone, despite it's deprecated, so unless I find a `GT-I9060` it's very difficult for me to debug.

However, I'll try to see if I can reproduce with any Android 4 I can find.

**Comment by WebReflection** [comment]
OK, I have a Geeksphone Revolution on Android 4.2.2 and ApplwWebkit/534.30 and also an Android 4.0.4 with the same version of the browser.

I have gotchas with attribute tests but nothing about the constructor.

At this point I need a page/use-case to test against or I won't be able to reproduce (also I have HTMLElement and its call method in their right place)

**Comment by WebReflection** [comment]
@cramforce ?

**Comment by cramforce** [comment]
Sorry, for not responding. As I said, we do not have a repro case. The error happens consistently, but only for a tiny percentage of page loads across a wide variety of AMP pages. Feel free to close it. I was mostly hoping you'd have an idea where to look.

**Comment by WebReflection** [comment]
Feel free to send me over one those phones 😄 

Btw, maybe switching to the latest would solve the issue? `1.4.1` does early patching in some device, it might fix this issue.

**Comment by cramforce** [comment]
Yeah, we'll definitely upgrade. Thanks!
