### ISSUE TITLE
Customized built-in elements don't work when they're cloned from a <template> element

### ISSUE THREAD

**Issue by serg-io** [WebReflection/document-register-element#92]
The attached [test.zip](https://github.com/WebReflection/document-register-element/files/615029/test.zip) file contains an index.html file that tests adding custom elements (v1) using multiple methods.

[Autonomous custom elements](https://html.spec.whatwg.org/multipage/scripting.html#custom-elements-autonomous-example) seem to work fine using all the methods to create and add them to the page.

However, [customized built-in elements](https://html.spec.whatwg.org/multipage/scripting.html#custom-elements-customized-builtin-example) don't work when they're cloned from a <template> element.

Here's the result I get using Chrome 54, 55, and 56:

![chrome-v54](https://cloud.githubusercontent.com/assets/1070007/20651832/80253c6c-b4a1-11e6-9958-4fb181265877.png)

Thank you in advance for looking into this issue.

**Comment by WebReflection** [comment]
the `innerHTML` case is special, as [described in the README](https://github.com/WebReflection/document-register-element#using-innerhtml)

The `cloneNode` seems to be fixed in non compliant browsers, I'll try to understand what is going on with Chrome.

Thanks

**Comment by WebReflection** [comment]
is this bug still relevant ?

**Comment by WebReflection** [comment]
no answers since May, not interested in solving this, not even sure it's still an issue so closing it for now.
