### ISSUE TITLE
Chrome components v1 native implementation - inner components problem

### ISSUE THREAD

**Issue by tnikolai2** [WebReflection/document-register-element#93]
for example :
HTML:   `'<tag1>aa<tag2></tag2>bb</tag1>'`

in tag1.connectedCallback  (at chrome native v1 implementation ) this.innerHTML  contain only "aa"
and this.childNodes contain one text node "aa".   `'<tag2></tag2>bb</tag1>'` appended only after component tag1 renderered. 

If i do: tag1.connectedCallback(){  this.innerHTML='xx';} 
result is  `'<tag1>xx<tag2></tag2>bb</tag1>'`

So at chrome native v1 implementation at  connectedCallback  
if component contain nested components, innerHTML and childNodes  contain only data before first inner component occurence. 

at v0 and non-native v1 implementation  innerHTML  all time contain correct value `'aa<tag2></tag2>bb'`

What can do with this problem?

Sample page:
```
<pre>
	class tag1 extends HTMLElement{
		connectedCallback(){console.log(this.innerHTML);  	this.innerHTML='xx' }
	}
	customElements.define('tag-1', tag1);
	customElements.define('tag-2', HTMLElement);
</pre>

First Variant(correct):  document.write('&lt;tag-1>aa&lt;tag-2> TAG2 &lt;/tag-2>bb&lt;/tag-1>')<br>
<script>
	class tag1 extends HTMLElement{
		connectedCallback(){console.log("innerHTML: "+this.innerHTML);  	this.innerHTML='xx' }
	}
	customElements.define('tag-1', tag1);
	customElements.define('tag-2', HTMLElement);
	
	document.write('<tag-1>aa<tag-2> TAG2 </tag-2>bb</tag-1>');
</script>

<br><br>Second Variant(incorrect)- in html: &lt;tag-1>aa&lt;tag-2> TAG2 &lt;/tag-2>bb&lt;/tag-1><br>
<tag-1>aa<tag-2> TAG2 </tag-2>bb</tag-1>

<br/><br/> <br/>  In second variant property innerHTML inside connectedCallback contains only data before first occurence of nested custom element.
Remainder appended after element will be rendered in any case, even if assign innerHTML empty string.
```

**Comment by WebReflection** [comment]
`innerHTML` is a special case:
https://github.com/WebReflection/document-register-element#using-innerhtml

**Comment by tnikolai2** [comment]
I use it:  innerHTML(this,'xx'); 
but result is same, problem left

**Comment by WebReflection** [comment]
OK, this bug as is is still invalid. Can you provide a very basic test/use case I can verify?

Such test won't be considered if you directly use `innerHTML` or `document.write`, thank you

**Comment by tnikolai2** [comment]
Oh, problem appear only if component static placed in HTML code, i think chrome do some optimization.

I long time try to fix this problem in static test page. And accidentally find out that my framework fully work on v1 at prodaction, because there added content only dynamically. So this problem newer occured.
