### ISSUE TITLE
Trouble on Firefox 50.1.0

### ISSUE THREAD

**Issue by micahscopes** [WebReflection/document-register-element#94]
This was working great for me up until recently.  Now I get NS_ERROR_NOT_IMPLEMENTED on Firefox 50.1.0

I ran the test and got 5 errors:
* V0: is="type" is a setup for known extends only (1, 1, 0)
* V0: constructor (1, 1, 0)
* V1: attributes notified on bootstrap (0, 1, 0)
* V1: customElements.whenDefined (0, 1, 0)
* V1: use extended to register and DOM to initialize (0, 1, 0)
* V1: use extended classes to register (1, 1, 0)

**Comment by WebReflection** [comment]
I just ran this page http://webreflection.github.io/document-register-element/test/ with Firefox 50.1.0 on Arch Linux and there's not a single red line.

![screenshot from 2017-01-08 16-11-21](https://cloud.githubusercontent.com/assets/85749/21751304/2d59c22c-d5bd-11e6-92ee-13df1057e17d.png)

**Comment by micahscopes** [comment]
@WebReflection I realized that this had something to do with having enabled webcomponents in about:config !

**Comment by kapouer** [comment]
Wow, i just got but by that snake for the whole evening and part of the night.
Isn't it possible to find a way to detect that non-working setup ?

**Comment by WebReflection** [comment]
Don’t enable experimental features.
If you do, deal with the experimental part of them.

**Comment by MikeVaz** [comment]
Hey Andrea! Is it a concern that current implementation of custom elements in FF breaks the unit tests? Because if it stays like this and they officially release it it might break code in prod. I tested my unit tests and two unit test are failing. I am trying FF v58.0b15 (64-bit).

**Comment by WebReflection** [comment]
I have no concerns. Firefox works.

![screenshot from 2018-01-12 09-11-35](https://user-images.githubusercontent.com/85749/34867609-af9dea0a-f778-11e7-8e2b-ac2dd59992ca.png)

**Comment by WebReflection** [comment]
P.S. I don't patch experimental features and I won't patch betas ... I don't care about these versions of the browser
