### ISSUE TITLE
Support Shadow DOM v1

### ISSUE THREAD

**Issue by dvoytenko** [WebReflection/document-register-element#96]
Safari 10 now comes with [Shadow DOM v1](https://www.w3.org/TR/shadow-dom/). The main API for creating shadow DOM is `attachShadow`.

Here's an example:
http://jsbin.com/norilag/1/edit?html,js,output

All `x-cust` elements should be instrumented, as happens with native implementation. However, in the current version of polyfill the first `x-cust` (inside the shadow) is not fully instrumented. More specifically, it's `connectedCallback` is never called. The same is probably true about other lifecycle callbacks, depending on when and how an element is created.

The issue is most likely with:
 1. `MutationObserver.observe(document, ...)` is not triggered inside shadow. It has to be redefined for each shadow root.
 2. `document.querySelectorAll` is not searching inside shadow. The search has to be repeated on shadow roots.

The solution would most likely involve patching `Element.prototype.attachShadow` and managing the known set of shadow roots.

/cc @amphtml-team @ampproject/amp-html-master-mergers @cramforce @erwinmombay

**Comment by WebReflection** [comment]
> The solution would most likely involve patching `Element.prototype.attachShadow` and managing the known set of shadow roots.

which browser that supports Shadow DOM v1 doesn't actually use native `customElements` and fallbacks to the polyfill, if I might ask?

**Comment by cramforce** [comment]
Unfortunately the currently shipping Safari has ShadowDOM but no Custom
Elements.

On Wed, Jan 11, 2017 at 9:51 AM, Andrea Giammarchi <notifications@github.com

**Comment by dvoytenko** [comment]
The best estimate we have is that CE will arrive on iOS Sept 2017, which means we'd likely have to live with SD/but-no-CE case on a big % of devices for at least 1-1.5 years.

**Comment by WebReflection** [comment]
IIRC this was already addressed and fixed:

https://github.com/WebReflection/document-register-element/blob/master/src/document-register-element.js#L496-L501

Can I please have a minimal example of failure to reproduce?

**Comment by dvoytenko** [comment]
@WebReflection The repro case in the jsbin link is in the description above. I used "1.1.1" version from cloudflare CDN. Should I try against another version?

**Comment by WebReflection** [comment]
current version is `1.3.0`

**Comment by WebReflection** [comment]
just had a look, it seems like Safari doesn't pass through the patched attachShadow.

I'll see what I can do.

**Comment by dvoytenko** [comment]
@WebReflection Hi! Thanks again for looking into this. I was wondering if you had any more info on this and if we could be of any assistance.

**Comment by WebReflection** [comment]
Apologies but I'm a full time employee and I'm preparing for a talk for [WCRemoteConf](https://wcremoteconf.com) on the coming Thursday, then I'll be snowboarding over the WE in Apls and I won't be able to work on this before next week.

Next week I'll try to sort this issue out. I hope that won't be too late.

Regards

**Comment by dvoytenko** [comment]
Not at all! Thanks a lot, @WebReflection !

**Comment by WebReflection** [comment]
I hope `v1.4.0` fixed the issue. I was lazily patching too many things, including the `attachShadow` but then of course, if you attach before ever defining a custom element, nothing would happen.

**Comment by WebReflection** [comment]
FYI the `1.4.0` had issues with native V0 when available, now fixed in `v1.4.1`

**Comment by dvoytenko** [comment]
Awesome! Thanks a lot, @WebReflection!
