### ISSUE TITLE
For V1 CE createdCallback is being called

### ISSUE THREAD

**Issue by tomalec** [WebReflection/document-register-element#99]
I'm not sure if it's a feature, a side-effect or a bug. But it hits me like a bug.

I'm so happy that thanks to `document-register-element` I'm finally able to gradually migrate my elements in big projects and run custom elements defined as v0 and v1 side by side.

However, I have few elements prepared in "hybrid" mode - they check by themselves the API version and use one or another. To DRY it a little, v1 constructor calls `createdCallback`, which happens to be called once again here https://github.com/WebReflection/document-register-element/blob/d3220462c33d7df2f898f59542cff1b07cf7dc6c/build/document-register-element.max.amd.js#L1262

```js
var MyElement;
if(window.customElements){
    MyElement = class MyElement extends HTMLElement {
        constructor(self){
            // https://github.com/WebReflection/document-register-element/tree/master#v1-caveat
            self = super(self);
            // Use createdCallback from v0
            MyElementProto.createdCallback.call(self);
            return self;
        }
    };
    MyElementProto = MyElement.prototype;
} else {
    MyElementProto = Object.create(HTMLElement.prototype);
}

MyElementProto.createdCallback = function() {/*...*/}
```

Is it so by design? Or would you like to support elements written for V! which also have `createdCallback` method?

**Comment by WebReflection** [comment]
> However, I have few elements prepared in "hybrid" mode

I think that's your problem. Drop the hybrid mode, either go V0 or V1. If you go V1, forget `createdCallback`.

If you want to lightly sort out every problems, use [CustomTag](https://github.com/WebReflection/custom-tag) and live happily ever after.

**Comment by tomalec** [comment]
Thanks for the quick response.
For future reference:
As I cannot guess on which environment my custom element would be used by someone else, and would like to remain as flexible as possible, without shipping two separate versions, I have worked it around with simple adding it to prototype only in v0:

```js
var MyElement;
if(window.customElements){
    MyElement = class MyElement extends HTMLElement {
        constructor(self){
            // https://github.com/WebReflection/document-register-element/tree/master#v1-caveat
            self = super(self);
            // Use createdCallback from v0
            createdCallback.call(self);
            return self;
        }
    };
    MyElementProto = MyElement.prototype;
} else {
    MyElementProto = Object.create(HTMLElement.prototype);
    MyElementProto.createdCallback = createdCallback;
}

function createdCallback() {/*...*/}
```

**Comment by WebReflection** [comment]
> I cannot guess on which environment my custom element would be

it's simple, either none or V1.

V0 shipped natively only on Chrome which meanwhile shipped V1 too.
Every other browser is either compatible with V1 or polyfilled.

With CustomTag you simply use `onInit`

**Comment by tomalec** [comment]
> it's simple, either none or V1.
Speaking of browsers, that enough.

But for complete envs in which my CE may run, some are still using for example webcomponentsjs with v0.
And I cannot require someone to migrate his/hers whole huge app, just because I'd like to gently use latest spec if available in my tiny element.

**Comment by WebReflection** [comment]
Fair enough. I just think that today I wouldn't waste time on V0 and everyone can just update their polyfill and use this one 🎉
